import 'package:http/http.dart' as http;
import 'dart:convert';

import 'package:http/http.dart';
import 'package:navigation_app/utils/sp_file_utils.dart';

class SpWS {
  static Map<String,Map<String, String>> _contentTypeMapByExtension;
  
  static Future<http.Response> post(String uri,
      {Map<String, String> headers, Map<String, String> parameters,
        body, Encoding encoding}) async {
    return _request(uri, method: RequestMethod.post,
        headers: headers,
        parameters: parameters,
        body: body,
        encoding: encoding);
  }

  static Future<http.Response> get(String uri,
      {Map<String, String> headers, Map<String, String> parameters,
      }) async {
    return _request(uri, method: RequestMethod.get,
        headers: headers,
        parameters: parameters);
  }

  static Future<http.Response> _request(String uri,
      {RequestMethod method, Map<String, String> parameters,
        Map<String, String> headers, body, Encoding encoding}) async {
    try {
      //print("SpWS.put - entry");
      encoding = encoding ?? Encoding.getByName('UTF8');

      parameters = parameters ?? Map<String, String>();
      final fullUri = SpWS.addQueryString(uri, parameters: parameters);

      // print(fullUrl);


    if (body is Map<String, String> && headers.containsValue('application/x-www-form-urlencoded')){
      //Do nothing but prevent body to fall throwgh the 'else' statement
    }
    else if (body is Map<String, dynamic>) {
    //console.log("Consideré esto un PlainObject: " + body)
      body = jsonEncode(body);
    }


      //console.log("antes de http.post");
      //console.log("fullUrl: " + fullUrl);
      //console.log("headers: " + JSON.stringify(headers));
      //console.log("body: " + body);
      //console.log("timeout: " + timeout);

      Response response;
      switch (method) {
        case RequestMethod.post:
          response = await http.post(Uri.parse(fullUri), headers: headers,
              body: body,
              encoding: encoding);
          break;
        case RequestMethod.get:
          response = await http.get(Uri.parse(fullUri), headers: headers);
          break;
        default:
          throw Exception('Method "$method" not supported.');
      }

      if (response.statusCode >= 200 && response.statusCode < 300) {
        return response;
      }
      else {

        throw Exception('Error al postear el request a la uri "$uri". Status Code: ${response.statusCode}. Error message: ${response.reasonPhrase}');
      }
    }
    on Exception catch (e) {
      throw e;
    }
  }

  static String addQueryString(String uri, {Map<String, String> parameters}) {
    var fullUri = uri;

    if (parameters != null) {
      var sep = '?';
      for (final item in parameters.entries) {
        fullUri += sep + '${item.key}=${item.value}';
        sep = '&';
      }
    }
    return fullUri;
  }

  static String getContentTypeFromFilePath(String filePath) {
    final fileExtension = SpFileUtils.getFileExtension(filePath);

    final contentTypeInfo = _getContentTypeMapByExtension()[fileExtension];

    if (contentTypeInfo == null){
      throw Exception('No content type value was found for file extension "$fileExtension".');
    }

    return contentTypeInfo['mimeType'];
  }

  static Map<String,Map<String, String>> _getContentTypeMapByExtension(){
    if(_contentTypeMapByExtension == null){
      _contentTypeMapByExtension = {
        '.ice': {'name': 'CoolTalk', 'mimeType': 'x-conference/x-cooltalk', 'fileExtension': '.ice'},
        '.movie': {'name': 'SGI Movie', 'mimeType': 'video/x-sgi-movie', 'fileExtension': '.movie'},
        '.avi': {'name': 'Audio Video Interleave (AVI)', 'mimeType': 'video/x-msvideo', 'fileExtension': '.avi'},
        '.wvx': {'name': 'Microsoft Windows Media Video Playlist', 'mimeType': 'video/x-ms-wvx', 'fileExtension': '.wvx'},
        '.wmx': {'name': 'Microsoft Windows Media Audio/Video Playlist', 'mimeType': 'video/x-ms-wmx', 'fileExtension': '.wmx'},
        '.wmv': {'name': 'Microsoft Windows Media Video', 'mimeType': 'video/x-ms-wmv', 'fileExtension': '.wmv'},
        '.wm': {'name': 'Microsoft Windows Media', 'mimeType': 'video/x-ms-wm', 'fileExtension': '.wm'},
        '.asf': {'name': 'Microsoft Advanced Systems Format (ASF)', 'mimeType': 'video/x-ms-asf', 'fileExtension': '.asf'},
        '.m4v': {'name': 'M4v', 'mimeType': 'video/x-m4v', 'fileExtension': '.m4v'},
        '.flv': {'name': 'Flash Video', 'mimeType': 'video/x-flv', 'fileExtension': '.flv'},
        '.fli': {'name': 'FLI/FLC Animation Format', 'mimeType': 'video/x-fli', 'fileExtension': '.fli'},
        '.f4v': {'name': 'Flash Video', 'mimeType': 'video/x-f4v', 'fileExtension': '.f4v'},
        '.webm': {'name': 'Open Web Media Project - Video', 'mimeType': 'video/webm', 'fileExtension': '.webm'},
        '.viv': {'name': 'Vivo', 'mimeType': 'video/vnd.vivo', 'fileExtension': '.viv'},
        '.uvu': {'name': 'DECE MP4', 'mimeType': 'video/vnd.uvvu.mp4', 'fileExtension': '.uvu'},
        '.pyv': {'name': 'Microsoft PlayReady Ecosystem Video', 'mimeType': 'video/vnd.ms-playready.media.pyv', 'fileExtension': '.pyv'},
        '.mxu': {'name': 'MPEG Url', 'mimeType': 'video/vnd.mpegurl', 'fileExtension': '.mxu'},
        '.fvt': {'name': 'FAST Search &amp; Transfer ASA', 'mimeType': 'video/vnd.fvt', 'fileExtension': '.fvt'},
        '.uvv': {'name': 'DECE Video', 'mimeType': 'video/vnd.dece.video', 'fileExtension': '.uvv'},
        '.uvs': {'name': 'DECE SD Video', 'mimeType': 'video/vnd.dece.sd', 'fileExtension': '.uvs'},
        '.uvp': {'name': 'DECE PD Video', 'mimeType': 'video/vnd.dece.pd', 'fileExtension': '.uvp'},
        '.uvm': {'name': 'DECE Mobile Video', 'mimeType': 'video/vnd.dece.mobile', 'fileExtension': '.uvm'},
        '.uvh': {'name': 'DECE High Definition Video', 'mimeType': 'video/vnd.dece.hd', 'fileExtension': '.uvh'},
        '.qt': {'name': 'Quicktime Video', 'mimeType': 'video/quicktime', 'fileExtension': '.qt'},
        '.ogv': {'name': 'Ogg Video', 'mimeType': 'video/ogg', 'fileExtension': '.ogv'},
        '.mpeg': {'name': 'MPEG Video', 'mimeType': 'video/mpeg', 'fileExtension': '.mpeg'},
        '.mp4': {'name': 'MPEG-4 Video', 'mimeType': 'video/mp4', 'fileExtension': '.mp4'},
        '.mj2': {'name': 'Motion JPEG 2000', 'mimeType': 'video/mj2', 'fileExtension': '.mj2'},
        '.jpm': {'name': 'JPEG 2000 Compound Image File Format', 'mimeType': 'video/jpm', 'fileExtension': '.jpm'},
        '.jpgv': {'name': 'JPGVideo', 'mimeType': 'video/jpeg', 'fileExtension': '.jpgv'},
        '.h264': {'name': 'H.264', 'mimeType': 'video/h264', 'fileExtension': '.h264'},
        '.h263': {'name': 'H.263', 'mimeType': 'video/h263', 'fileExtension': '.h263'},
        '.h261': {'name': 'H.261', 'mimeType': 'video/h261', 'fileExtension': '.h261'},
        '.3g2': {'name': '3GP2', 'mimeType': 'video/3gpp2', 'fileExtension': '.3g2'},
        '.3gp': {'name': '3GP', 'mimeType': 'video/3gpp', 'fileExtension': '.3gp'},
        '.yaml': {'name': "YAML Ain't Markup Language / Yet Another Markup Language", 'mimeType': 'text/yaml', 'fileExtension': '.yaml'},
        '.vcf': {'name': 'vCard', 'mimeType': 'text/x-vcard', 'fileExtension': '.vcf'},
        '.vcs': {'name': 'vCalendar', 'mimeType': 'text/x-vcalendar', 'fileExtension': '.vcs'},
        '.uu': {'name': 'UUEncode', 'mimeType': 'text/x-uuencode', 'fileExtension': '.uu'},
        '.etx': {'name': 'Setext', 'mimeType': 'text/x-setext', 'fileExtension': '.etx'},
        '.p': {'name': 'Pascal Source File', 'mimeType': 'text/x-pascal', 'fileExtension': '.p'},
        '.java': {'name': 'Java Source File', 'mimeType': 'text/x-java-source,java', 'fileExtension': '.java'},
        '.f': {'name': 'Fortran Source File', 'mimeType': 'text/x-fortran', 'fileExtension': '.f'},
        '.c': {'name': 'C Source File', 'mimeType': 'text/x-c', 'fileExtension': '.c'},
        '.s': {'name': 'Assembler Source File', 'mimeType': 'text/x-asm', 'fileExtension': '.s'},
        '.wmls': {'name': 'Wireless Markup Language Script (WMLScript)', 'mimeType': 'text/vnd.wap.wmlscript', 'fileExtension': '.wmls'},
        '.wml': {'name': 'Wireless Markup Language (WML)', 'mimeType': 'text/vnd.wap.wml', 'fileExtension': '.wml'},
        '.jad': {'name': 'J2ME App Descriptor', 'mimeType': 'text/vnd.sun.j2me.app-descriptor', 'fileExtension': '.jad'},
        '.spot': {'name': 'In3D - 3DML', 'mimeType': 'text/vnd.in3d.spot', 'fileExtension': '.spot'},
        '.3dml': {'name': 'In3D - 3DML', 'mimeType': 'text/vnd.in3d.3dml', 'fileExtension': '.3dml'},
        '.gv': {'name': 'Graphviz', 'mimeType': 'text/vnd.graphviz', 'fileExtension': '.gv'},
        '.flx': {'name': 'FLEXSTOR', 'mimeType': 'text/vnd.fmi.flexstor', 'fileExtension': '.flx'},
        '.fly': {'name': 'mod_fly / fly.cgi', 'mimeType': 'text/vnd.fly', 'fileExtension': '.fly'},
        '.scurl': {'name': 'Curl - Source Code', 'mimeType': 'text/vnd.curl.scurl', 'fileExtension': '.scurl'},
        '.mcurl': {'name': 'Curl - Manifest File', 'mimeType': 'text/vnd.curl.mcurl', 'fileExtension': '.mcurl'},
        '.dcurl': {'name': 'Curl - Detached Applet', 'mimeType': 'text/vnd.curl.dcurl', 'fileExtension': '.dcurl'},
        '.curl': {'name': 'Curl - Applet', 'mimeType': 'text/vnd.curl', 'fileExtension': '.curl'},
        '.uri': {'name': 'URI Resolution Services', 'mimeType': 'text/uri-list', 'fileExtension': '.uri'},
        '.ttl': {'name': 'Turtle (Terse RDF Triple Language)', 'mimeType': 'text/turtle', 'fileExtension': '.ttl'},
        '.t': {'name': 'troff', 'mimeType': 'text/troff', 'fileExtension': '.t'},
        '.tsv': {'name': 'Tab Seperated Values', 'mimeType': 'text/tab-separated-values', 'fileExtension': '.tsv'},
        '.sgml': {'name': 'Standard Generalized Markup Language (SGML)', 'mimeType': 'text/sgml', 'fileExtension': '.sgml'},
        '.rtx': {'name': 'Rich Text Format (RTF)', 'mimeType': 'text/richtext', 'fileExtension': '.rtx'},
        '.dsc': {'name': 'PRS Lines Tag', 'mimeType': 'text/prs.lines.tag', 'fileExtension': '.dsc'},
        '.par': {'name': 'BAS Partitur Format', 'mimeType': 'text/plain-bas', 'fileExtension': '.par'},
        '.txt': {'name': 'Text File', 'mimeType': 'text/plain', 'fileExtension': '.txt'},
        '.n3': {'name': 'Notation3', 'mimeType': 'text/n3', 'fileExtension': '.n3'},
        '.html': {'name': 'HyperText Markup Language (HTML)', 'mimeType': 'text/html', 'fileExtension': '.html'},
        '.csv': {'name': 'Comma-Seperated Values', 'mimeType': 'text/csv', 'fileExtension': '.csv'},
        '.css': {'name': 'Cascading Style Sheets (CSS)', 'mimeType': 'text/css', 'fileExtension': '.css'},
        '.ics': {'name': 'iCalendar', 'mimeType': 'text/calendar', 'fileExtension': '.ics'},
        '.wrl': {'name': 'Virtual Reality Modeling Language', 'mimeType': 'model/vrml', 'fileExtension': '.wrl'},
        '.vtu': {'name': 'Virtue VTU', 'mimeType': 'model/vnd.vtu', 'fileExtension': '.vtu'},
        '.mts': {'name': 'Virtue MTS', 'mimeType': 'model/vnd.mts', 'fileExtension': '.mts'},
        '.gtw': {'name': 'Gen-Trix Studio', 'mimeType': 'model/vnd.gtw', 'fileExtension': '.gtw'},
        '.gdl': {'name': 'Geometric Description Language (GDL)', 'mimeType': 'model/vnd.gdl', 'fileExtension': '.gdl'},
        '.dwf': {'name': 'Autodesk Design Web Format (DWF)', 'mimeType': 'model/vnd.dwf', 'fileExtension': '.dwf'},
        '.dae': {'name': 'COLLADA', 'mimeType': 'model/vnd.collada+xml', 'fileExtension': '.dae'},
        '.msh': {'name': 'Mesh Data Type', 'mimeType': 'model/mesh', 'fileExtension': '.msh'},
        '.igs': {'name': 'Initial Graphics Exchange Specification (IGES)', 'mimeType': 'model/iges', 'fileExtension': '.igs'},
        '.eml': {'name': 'Email Message', 'mimeType': 'message/rfc822', 'fileExtension': '.eml'},
        '.xwd': {'name': 'X Window Dump', 'mimeType': 'image/x-xwindowdump', 'fileExtension': '.xwd'},
        '.xpm': {'name': 'X PixMap', 'mimeType': 'image/x-xpixmap', 'fileExtension': '.xpm'},
        '.xbm': {'name': 'X BitMap', 'mimeType': 'image/x-xbitmap', 'fileExtension': '.xbm'},
        '.rgb': {'name': 'Silicon Graphics RGB Bitmap', 'mimeType': 'image/x-rgb', 'fileExtension': '.rgb'},
        '.ppm': {'name': 'Portable Pixmap Format', 'mimeType': 'image/x-portable-pixmap', 'fileExtension': '.ppm'},
        '.pgm': {'name': 'Portable Graymap Format', 'mimeType': 'image/x-portable-graymap', 'fileExtension': '.pgm'},
        '.pbm': {'name': 'Portable Bitmap Format', 'mimeType': 'image/x-portable-bitmap', 'fileExtension': '.pbm'},
        '.pnm': {'name': 'Portable Anymap Image', 'mimeType': 'image/x-portable-anymap', 'fileExtension': '.pnm'},
        '.png': {'name': 'Portable Network Graphics (PNG) (x-token)', 'mimeType': 'image/x-png', 'fileExtension': '.png'},
        '.pic': {'name': 'PICT Image', 'mimeType': 'image/x-pict', 'fileExtension': '.pic'},
        '.pcx': {'name': 'PCX Image', 'mimeType': 'image/x-pcx', 'fileExtension': '.pcx'},
        '.ico': {'name': 'Icon Image', 'mimeType': 'image/x-icon', 'fileExtension': '.ico'},
        '.fh': {'name': 'FreeHand MX', 'mimeType': 'image/x-freehand', 'fileExtension': '.fh'},
        '.cmx': {'name': 'Corel Metafile Exchange (CMX)', 'mimeType': 'image/x-cmx', 'fileExtension': '.cmx'},
        '.ras': {'name': 'CMU Image', 'mimeType': 'image/x-cmu-raster', 'fileExtension': '.ras'},
        '.png': {'name': 'Portable Network Graphics (PNG) (Citrix client)', 'mimeType': 'image/x-citrix-png', 'fileExtension': '.png'},
        '.jpeg, .jpg': {'name': 'JPEG Image (Citrix client)', 'mimeType': 'image/x-citrix-jpeg', 'fileExtension': '.jpeg, .jpg'},
        '.webp': {'name': 'WebP Image', 'mimeType': 'image/webp', 'fileExtension': '.webp'},
        '.xif': {'name': 'eXtended Image File Format (XIFF)', 'mimeType': 'image/vnd.xiff', 'fileExtension': '.xif'},
        '.wbmp': {'name': 'WAP Bitamp (WBMP)', 'mimeType': 'image/vnd.wap.wbmp', 'fileExtension': '.wbmp'},
        '.npx': {'name': 'FlashPix', 'mimeType': 'image/vnd.net-fpx', 'fileExtension': '.npx'},
        '.mdi': {'name': 'Microsoft Document Imaging Format', 'mimeType': 'image/vnd.ms-modi', 'fileExtension': '.mdi'},
        '.rlc': {'name': 'EDMICS 2000', 'mimeType': 'image/vnd.fujixerox.edmics-rlc', 'fileExtension': '.rlc'},
        '.mmr': {'name': 'EDMICS 2000', 'mimeType': 'image/vnd.fujixerox.edmics-mmr', 'fileExtension': '.mmr'},
        '.fst': {'name': 'FAST Search &amp; Transfer ASA', 'mimeType': 'image/vnd.fst', 'fileExtension': '.fst'},
        '.fpx': {'name': 'FlashPix', 'mimeType': 'image/vnd.fpx', 'fileExtension': '.fpx'},
        '.fbs': {'name': 'FastBid Sheet', 'mimeType': 'image/vnd.fastbidsheet', 'fileExtension': '.fbs'},
        '.dxf': {'name': 'AutoCAD DXF', 'mimeType': 'image/vnd.dxf', 'fileExtension': '.dxf'},
        '.dwg': {'name': 'DWG Drawing', 'mimeType': 'image/vnd.dwg', 'fileExtension': '.dwg'},
        '.sub': {'name': 'Close Captioning - Subtitle', 'mimeType': 'image/vnd.dvb.subtitle', 'fileExtension': '.sub'},
        '.djvu': {'name': 'DjVu', 'mimeType': 'image/vnd.djvu', 'fileExtension': '.djvu'},
        '.uvi': {'name': 'DECE Graphic', 'mimeType': 'image/vnd.dece.graphic', 'fileExtension': '.uvi'},
        '.psd': {'name': 'Photoshop Document', 'mimeType': 'image/vnd.adobe.photoshop', 'fileExtension': '.psd'},
        '.tiff': {'name': 'Tagged Image File Format', 'mimeType': 'image/tiff', 'fileExtension': '.tiff'},
        '.svg': {'name': 'Scalable Vector Graphics (SVG)', 'mimeType': 'image/svg+xml', 'fileExtension': '.svg'},
        '.btif': {'name': 'BTIF', 'mimeType': 'image/prs.btif', 'fileExtension': '.btif'},
        '.png': {'name': 'Portable Network Graphics (PNG)', 'mimeType': 'image/png', 'fileExtension': '.png'},
        '.pjpeg': {'name': 'JPEG Image (Progressive)', 'mimeType': 'image/pjpeg', 'fileExtension': '.pjpeg'},
        '.ktx': {'name': 'OpenGL Textures (KTX)', 'mimeType': 'image/ktx', 'fileExtension': '.ktx'},
        '.jpeg': {'name': 'JPEG Image', 'mimeType': 'image/jpeg', 'fileExtension': '.jpeg'},
        '.jpg': {'name': 'JPEG Image', 'mimeType': 'image/jpeg', 'fileExtension': '.jpg'},
        '.ief': {'name': 'Image Exchange Format', 'mimeType': 'image/ief', 'fileExtension': '.ief'},
        '.gif': {'name': 'Graphics Interchange Format', 'mimeType': 'image/gif', 'fileExtension': '.gif'},
        '.g3': {'name': 'G3 Fax Image', 'mimeType': 'image/g3fax', 'fileExtension': '.g3'},
        '.cgm': {'name': 'Computer Graphics Metafile', 'mimeType': 'image/cgm', 'fileExtension': '.cgm'},
        '.bmp': {'name': 'Bitmap Image File', 'mimeType': 'image/bmp', 'fileExtension': '.bmp'},
        '.xyz': {'name': 'XYZ File Format', 'mimeType': 'chemical/x-xyz', 'fileExtension': '.xyz'},
        '.csml': {'name': 'Chemical Style Markup Language', 'mimeType': 'chemical/x-csml', 'fileExtension': '.csml'},
        '.cml': {'name': 'Chemical Markup Language', 'mimeType': 'chemical/x-cml', 'fileExtension': '.cml'},
        '.cmdf': {'name': 'CrystalMaker Data Format', 'mimeType': 'chemical/x-cmdf', 'fileExtension': '.cmdf'},
        '.cif': {'name': 'Crystallographic Interchange Format', 'mimeType': 'chemical/x-cif', 'fileExtension': '.cif'},
        '.cdx': {'name': 'ChemDraw eXchange file', 'mimeType': 'chemical/x-cdx', 'fileExtension': '.cdx'},
        '.wav': {'name': 'Waveform Audio File Format (WAV)', 'mimeType': 'audio/x-wav', 'fileExtension': '.wav'},
        '.rmp': {'name': 'Real Audio Sound', 'mimeType': 'audio/x-pn-realaudio-plugin', 'fileExtension': '.rmp'},
        '.ram': {'name': 'Real Audio Sound', 'mimeType': 'audio/x-pn-realaudio', 'fileExtension': '.ram'},
        '.wma': {'name': 'Microsoft Windows Media Audio', 'mimeType': 'audio/x-ms-wma', 'fileExtension': '.wma'},
        '.wax': {'name': 'Microsoft Windows Media Audio Redirector', 'mimeType': 'audio/x-ms-wax', 'fileExtension': '.wax'},
        '.m3u': {'name': 'M3U (Multimedia Playlist)', 'mimeType': 'audio/x-mpegurl', 'fileExtension': '.m3u'},
        '.aif': {'name': 'Audio Interchange File Format', 'mimeType': 'audio/x-aiff', 'fileExtension': '.aif'},
        '.aac': {'name': 'Advanced Audio Coding (AAC)', 'mimeType': 'audio/x-aac', 'fileExtension': '.aac'},
        '.weba': {'name': 'Open Web Media Project - Audio', 'mimeType': 'audio/webm', 'fileExtension': '.weba'},
        '.rip': {'name': "Hit'n'Mix", 'mimeType': 'audio/vnd.rip', 'fileExtension': '.rip'},
        '.ecelp9600': {'name': 'Nuera ECELP 9600', 'mimeType': 'audio/vnd.nuera.ecelp9600', 'fileExtension': '.ecelp9600'},
        '.ecelp7470': {'name': 'Nuera ECELP 7470', 'mimeType': 'audio/vnd.nuera.ecelp7470', 'fileExtension': '.ecelp7470'},
        '.ecelp4800': {'name': 'Nuera ECELP 4800', 'mimeType': 'audio/vnd.nuera.ecelp4800', 'fileExtension': '.ecelp4800'},
        '.pya': {'name': 'Microsoft PlayReady Ecosystem', 'mimeType': 'audio/vnd.ms-playready.media.pya', 'fileExtension': '.pya'},
        '.lvp': {'name': 'Lucent Voice', 'mimeType': 'audio/vnd.lucent.voice', 'fileExtension': '.lvp'},
        '.dtshd': {'name': 'DTS High Definition Audio', 'mimeType': 'audio/vnd.dts.hd', 'fileExtension': '.dtshd'},
        '.dts': {'name': 'DTS Audio', 'mimeType': 'audio/vnd.dts', 'fileExtension': '.dts'},
        '.dra': {'name': 'DRA Audio', 'mimeType': 'audio/vnd.dra', 'fileExtension': '.dra'},
        '.eol': {'name': 'Digital Winds Music', 'mimeType': 'audio/vnd.digital-winds', 'fileExtension': '.eol'},
        '.uva': {'name': 'DECE Audio', 'mimeType': 'audio/vnd.dece.audio', 'fileExtension': '.uva'},
        '.oga': {'name': 'Ogg Audio', 'mimeType': 'audio/ogg', 'fileExtension': '.oga'},
        '.mpga': {'name': 'MPEG Audio', 'mimeType': 'audio/mpeg', 'fileExtension': '.mpga'},
        '.mp4a': {'name': 'MPEG-4 Audio', 'mimeType': 'audio/mp4', 'fileExtension': '.mp4a'},
        '.mid': {'name': 'MIDI - Musical Instrument Digital Interface', 'mimeType': 'audio/midi', 'fileExtension': '.mid'},
        '.au': {'name': 'Sun Audio - Au file format', 'mimeType': 'audio/basic', 'fileExtension': '.au'},
        '.adp': {'name': 'Adaptive differential pulse-code modulation', 'mimeType': 'audio/adpcm', 'fileExtension': '.adp'},
        '.zip': {'name': 'Zip Archive', 'mimeType': 'application/zip', 'fileExtension': '.zip'},
        '.yin': {'name': 'YIN (YANG - XML)', 'mimeType': 'application/yin+xml', 'fileExtension': '.yin'},
        '.yang': {'name': 'YANG Data Modeling Language', 'mimeType': 'application/yang', 'fileExtension': '.yang'},
        '.mxml': {'name': 'MXML', 'mimeType': 'application/xv+xml', 'fileExtension': '.mxml'},
        '.xspf': {'name': 'XSPF - XML Shareable Playlist Format', 'mimeType': 'application/xspf+xml', 'fileExtension': '.xspf'},
        '.xslt': {'name': 'XML Transformations', 'mimeType': 'application/xslt+xml', 'fileExtension': '.xslt'},
        '.xop': {'name': 'XML-Binary Optimized Packaging', 'mimeType': 'application/xop+xml', 'fileExtension': '.xop'},
        '.dtd': {'name': 'Document Type Definition', 'mimeType': 'application/xml-dtd', 'fileExtension': '.dtd'},
        '.xml': {'name': 'XML - Extensible Markup Language', 'mimeType': 'application/xml', 'fileExtension': '.xml'},
        '.xhtml': {'name': 'XHTML - The Extensible HyperText Markup Language', 'mimeType': 'application/xhtml+xml', 'fileExtension': '.xhtml'},
        '.xenc': {'name': 'XML Encryption Syntax and Processing', 'mimeType': 'application/xenc+xml', 'fileExtension': '.xenc'},
        '.xdf': {'name': 'XML Configuration Access Protocol - XCAP Diff', 'mimeType': 'application/xcap-diff+xml', 'fileExtension': '.xdf'},
        '.xpi': {'name': 'XPInstall - Mozilla', 'mimeType': 'application/x-xpinstall', 'fileExtension': '.xpi'},
        '.fig': {'name': 'Xfig', 'mimeType': 'application/x-xfig', 'fileExtension': '.fig'},
        '.der': {'name': 'X.509 Certificate', 'mimeType': 'application/x-x509-ca-cert', 'fileExtension': '.der'},
        '.src': {'name': 'WAIS Source', 'mimeType': 'application/x-wais-source', 'fileExtension': '.src'},
        '.ustar': {'name': 'Ustar (Uniform Standard Tape Archive)', 'mimeType': 'application/x-ustar', 'fileExtension': '.ustar'},
        '.texinfo': {'name': 'GNU Texinfo Document', 'mimeType': 'application/x-texinfo', 'fileExtension': '.texinfo'},
        '.tfm': {'name': 'TeX Font Metric', 'mimeType': 'application/x-tex-tfm', 'fileExtension': '.tfm'},
        '.tex': {'name': 'TeX', 'mimeType': 'application/x-tex', 'fileExtension': '.tex'},
        '.tcl': {'name': 'Tcl Script', 'mimeType': 'application/x-tcl', 'fileExtension': '.tcl'},
        '.tar': {'name': 'Tar File (Tape Archive)', 'mimeType': 'application/x-tar', 'fileExtension': '.tar'},
        '.sv4crc': {'name': 'System V Release 4 CPIO Checksum Data', 'mimeType': 'application/x-sv4crc', 'fileExtension': '.sv4crc'},
        '.sv4cpio': {'name': 'System V Release 4 CPIO Archive', 'mimeType': 'application/x-sv4cpio', 'fileExtension': '.sv4cpio'},
        '.sitx': {'name': 'Stuffit Archive', 'mimeType': 'application/x-stuffitx', 'fileExtension': '.sitx'},
        '.sit': {'name': 'Stuffit Archive', 'mimeType': 'application/x-stuffit', 'fileExtension': '.sit'},
        '.xap': {'name': 'Microsoft Silverlight', 'mimeType': 'application/x-silverlight-app', 'fileExtension': '.xap'},
        '.swf': {'name': 'Adobe Flash', 'mimeType': 'application/x-shockwave-flash', 'fileExtension': '.swf'},
        '.shar': {'name': 'Shell Archive', 'mimeType': 'application/x-shar', 'fileExtension': '.shar'},
        '.sh': {'name': 'Bourne Shell Script', 'mimeType': 'application/x-sh', 'fileExtension': '.sh'},
        '.rar': {'name': 'RAR Archive', 'mimeType': 'application/x-rar-compressed', 'fileExtension': '.rar'},
        '.p7r': {'name': 'PKCS #7 - Cryptographic Message Syntax Standard (Certificate Request Response)', 'mimeType': 'application/x-pkcs7-certreqresp', 'fileExtension': '.p7r'},
        '.p7b': {'name': 'PKCS #7 - Cryptographic Message Syntax Standard (Certificates)', 'mimeType': 'application/x-pkcs7-certificates', 'fileExtension': '.p7b'},
        '.p12': {'name': 'PKCS #12 - Personal Information Exchange Syntax Standard', 'mimeType': 'application/x-pkcs12', 'fileExtension': '.p12'},
        '.nc': {'name': 'Network Common Data Form (NetCDF)', 'mimeType': 'application/x-netcdf', 'fileExtension': '.nc'},
        '.wri': {'name': 'Microsoft Wordpad', 'mimeType': 'application/x-mswrite', 'fileExtension': '.wri'},
        '.trm': {'name': 'Microsoft Windows Terminal Services', 'mimeType': 'application/x-msterminal', 'fileExtension': '.trm'},
        '.scd': {'name': 'Microsoft Schedule+', 'mimeType': 'application/x-msschedule', 'fileExtension': '.scd'},
        '.pub': {'name': 'Microsoft Publisher', 'mimeType': 'application/x-mspublisher', 'fileExtension': '.pub'},
        '.mny': {'name': 'Microsoft Money', 'mimeType': 'application/x-msmoney', 'fileExtension': '.mny'},
        '.wmf': {'name': 'Microsoft Windows Metafile', 'mimeType': 'application/x-msmetafile', 'fileExtension': '.wmf'},
        '.mvb': {'name': 'Microsoft MediaView', 'mimeType': 'application/x-msmediaview', 'fileExtension': '.mvb'},
        '.exe': {'name': 'Microsoft Application', 'mimeType': 'application/x-msdownload', 'fileExtension': '.exe'},
        '.clp': {'name': 'Microsoft Clipboard Clip', 'mimeType': 'application/x-msclip', 'fileExtension': '.clp'},
        '.crd': {'name': 'Microsoft Information Card', 'mimeType': 'application/x-mscardfile', 'fileExtension': '.crd'},
        '.obd': {'name': 'Microsoft Office Binder', 'mimeType': 'application/x-msbinder', 'fileExtension': '.obd'},
        '.mdb': {'name': 'Microsoft Access', 'mimeType': 'application/x-msaccess', 'fileExtension': '.mdb'},
        '.xbap': {'name': 'Microsoft XAML Browser Application', 'mimeType': 'application/x-ms-xbap', 'fileExtension': '.xbap'},
        '.wmz': {'name': 'Microsoft Windows Media Player Skin Package', 'mimeType': 'application/x-ms-wmz', 'fileExtension': '.wmz'},
        '.wmd': {'name': 'Microsoft Windows Media Player Download Package', 'mimeType': 'application/x-ms-wmd', 'fileExtension': '.wmd'},
        '.application': {'name': 'Microsoft ClickOnce', 'mimeType': 'application/x-ms-application', 'fileExtension': '.application'},
        '.prc': {'name': 'Mobipocket', 'mimeType': 'application/x-mobipocket-ebook', 'fileExtension': '.prc'},
        '.latex': {'name': 'LaTeX', 'mimeType': 'application/x-latex', 'fileExtension': '.latex'},
        '.jnlp': {'name': 'Java Network Launching Protocol', 'mimeType': 'application/x-java-jnlp-file', 'fileExtension': '.jnlp'},
        '.hdf': {'name': 'Hierarchical Data Format', 'mimeType': 'application/x-hdf', 'fileExtension': '.hdf'},
        '.gtar': {'name': 'GNU Tar Files', 'mimeType': 'application/x-gtar', 'fileExtension': '.gtar'},
        '.gnumeric': {'name': 'Gnumeric', 'mimeType': 'application/x-gnumeric', 'fileExtension': '.gnumeric'},
        '.spl': {'name': 'FutureSplash Animator', 'mimeType': 'application/x-futuresplash', 'fileExtension': '.spl'},
        '.woff': {'name': 'Web Open Font Format', 'mimeType': 'application/x-font-woff', 'fileExtension': '.woff'},
        '.pfa': {'name': 'PostScript Fonts', 'mimeType': 'application/x-font-type1', 'fileExtension': '.pfa'},
        '.ttf': {'name': 'TrueType Font', 'mimeType': 'application/x-font-ttf', 'fileExtension': '.ttf'},
        '.snf': {'name': 'Server Normal Format', 'mimeType': 'application/x-font-snf', 'fileExtension': '.snf'},
        '.pcf': {'name': 'Portable Compiled Format', 'mimeType': 'application/x-font-pcf', 'fileExtension': '.pcf'},
        '.otf': {'name': 'OpenType Font File', 'mimeType': 'application/x-font-otf', 'fileExtension': '.otf'},
        '.psf': {'name': 'PSF Fonts', 'mimeType': 'application/x-font-linux-psf', 'fileExtension': '.psf'},
        '.gsf': {'name': 'Ghostscript Font', 'mimeType': 'application/x-font-ghostscript', 'fileExtension': '.gsf'},
        '.bdf': {'name': 'Glyph Bitmap Distribution Format', 'mimeType': 'application/x-font-bdf', 'fileExtension': '.bdf'},
        '.dvi': {'name': 'Device Independent File Format (DVI)', 'mimeType': 'application/x-dvi', 'fileExtension': '.dvi'},
        '.res': {'name': 'Digital Talking Book - Resource File', 'mimeType': 'application/x-dtbresource+xml', 'fileExtension': '.res'},
        '.dtb': {'name': 'Digital Talking Book', 'mimeType': 'application/x-dtbook+xml', 'fileExtension': '.dtb'},
        '.ncx': {'name': 'Navigation Control file for XML (for ePub)', 'mimeType': 'application/x-dtbncx+xml', 'fileExtension': '.ncx'},
        '.wad': {'name': 'Doom Video Game', 'mimeType': 'application/x-doom', 'fileExtension': '.wad'},
        '.dir': {'name': 'Adobe Shockwave Player', 'mimeType': 'application/x-director', 'fileExtension': '.dir'},
        '.deb': {'name': 'Debian Package', 'mimeType': 'application/x-debian-package', 'fileExtension': '.deb'},
        '.csh': {'name': 'C Shell Script', 'mimeType': 'application/x-csh', 'fileExtension': '.csh'},
        '.cpio': {'name': 'CPIO Archive', 'mimeType': 'application/x-cpio', 'fileExtension': '.cpio'},
        '.pgn': {'name': 'Portable Game Notation (Chess Games)', 'mimeType': 'application/x-chess-pgn', 'fileExtension': '.pgn'},
        '.chat': {'name': 'pIRCh', 'mimeType': 'application/x-chat', 'fileExtension': '.chat'},
        '.vcd': {'name': 'Video CD', 'mimeType': 'application/x-cdlink', 'fileExtension': '.vcd'},
        '.bz2': {'name': 'Bzip2 Archive', 'mimeType': 'application/x-bzip2', 'fileExtension': '.bz2'},
        '.bz': {'name': 'Bzip Archive', 'mimeType': 'application/x-bzip', 'fileExtension': '.bz'},
        '.torrent': {'name': 'BitTorrent', 'mimeType': 'application/x-bittorrent', 'fileExtension': '.torrent'},
        '.bcpio': {'name': 'Binary CPIO Archive', 'mimeType': 'application/x-bcpio', 'fileExtension': '.bcpio'},
        '.aas': {'name': 'Adobe (Macropedia) Authorware - Segment File', 'mimeType': 'application/x-authorware-seg', 'fileExtension': '.aas'},
        '.aam': {'name': 'Adobe (Macropedia) Authorware - Map', 'mimeType': 'application/x-authorware-map', 'fileExtension': '.aam'},
        '.aab': {'name': 'Adobe (Macropedia) Authorware - Binary File', 'mimeType': 'application/x-authorware-bin', 'fileExtension': '.aab'},
        '.dmg': {'name': 'Apple Disk Image', 'mimeType': 'application/x-apple-diskimage', 'fileExtension': '.dmg'},
        '.ace': {'name': 'Ace Archive', 'mimeType': 'application/x-ace-compressed', 'fileExtension': '.ace'},
        '.abw': {'name': 'AbiWord', 'mimeType': 'application/x-abiword', 'fileExtension': '.abw'},
        '.7z': {'name': '7-Zip', 'mimeType': 'application/x-7z-compressed', 'fileExtension': '.7z'},
        '.wspolicy': {'name': 'Web Services Policy', 'mimeType': 'application/wspolicy+xml', 'fileExtension': '.wspolicy'},
        '.wsdl': {'name': 'WSDL - Web Services Description Language', 'mimeType': 'application/wsdl+xml', 'fileExtension': '.wsdl'},
        '.hlp': {'name': 'WinHelp', 'mimeType': 'application/winhlp', 'fileExtension': '.hlp'},
        '.wgt': {'name': 'Widget Packaging and XML Configuration', 'mimeType': 'application/widget', 'fileExtension': '.wgt'},
        '.vxml': {'name': 'VoiceXML', 'mimeType': 'application/voicexml+xml', 'fileExtension': '.vxml'},
        '.zaz': {'name': 'Zzazz Deck', 'mimeType': 'application/vnd.zzazz.deck+xml', 'fileExtension': '.zaz'},
        '.zir': {'name': 'Z.U.L. Geometry', 'mimeType': 'application/vnd.zul', 'fileExtension': '.zir'},
        '.cmp': {'name': 'CustomMenu', 'mimeType': 'application/vnd.yellowriver-custom-menu', 'fileExtension': '.cmp'},
        '.spf': {'name': 'SMAF Phrase', 'mimeType': 'application/vnd.yamaha.smaf-phrase', 'fileExtension': '.spf'},
        '.saf': {'name': 'SMAF Audio', 'mimeType': 'application/vnd.yamaha.smaf-audio', 'fileExtension': '.saf'},
        '.osfpvg': {'name': 'OSFPVG', 'mimeType': 'application/vnd.yamaha.openscoreformat.osfpvg+xml', 'fileExtension': '.osfpvg'},
        '.osf': {'name': 'Open Score Format', 'mimeType': 'application/vnd.yamaha.openscoreformat', 'fileExtension': '.osf'},
        '.hvp': {'name': 'HV Voice Parameter', 'mimeType': 'application/vnd.yamaha.hv-voice', 'fileExtension': '.hvp'},
        '.hvs': {'name': 'HV Script', 'mimeType': 'application/vnd.yamaha.hv-script', 'fileExtension': '.hvs'},
        '.hvd': {'name': 'HV Voice Dictionary', 'mimeType': 'application/vnd.yamaha.hv-dic', 'fileExtension': '.hvd'},
        '.xfdl': {'name': 'Extensible Forms Description Language', 'mimeType': 'application/vnd.xfdl', 'fileExtension': '.xfdl'},
        '.xar': {'name': 'CorelXARA', 'mimeType': 'application/vnd.xara', 'fileExtension': '.xar'},
        '.stf': {'name': 'Worldtalk', 'mimeType': 'application/vnd.wt.stf', 'fileExtension': '.stf'},
        '.wqd': {'name': 'SundaHus WQ', 'mimeType': 'application/vnd.wqd', 'fileExtension': '.wqd'},
        '.wpd': {'name': 'Wordperfect', 'mimeType': 'application/vnd.wordperfect', 'fileExtension': '.wpd'},
        '.nbp': {'name': 'Mathematica Notebook Player', 'mimeType': 'application/vnd.wolfram.player', 'fileExtension': '.nbp'},
        '.wtb': {'name': 'WebTurbo', 'mimeType': 'application/vnd.webturbo', 'fileExtension': '.wtb'},
        '.wmlsc': {'name': 'WMLScript', 'mimeType': 'application/vnd.wap.wmlscriptc', 'fileExtension': '.wmlsc'},
        '.wmlc': {'name': 'Compiled Wireless Markup Language (WMLC)', 'mimeType': 'application/vnd.wap.wmlc', 'fileExtension': '.wmlc'},
        '.wbxml': {'name': 'WAP Binary XML (WBXML)', 'mimeType': 'application/vnd.wap.wbxml', 'fileExtension': '.wbxml'},
        '.vsf': {'name': 'Viewport+', 'mimeType': 'application/vnd.vsf', 'fileExtension': '.vsf'},
        '.vis': {'name': 'Visionary', 'mimeType': 'application/vnd.visionary', 'fileExtension': '.vis'},
        '.vsdx': {'name': 'Microsoft Visio 2013', 'mimeType': 'application/vnd.visio2013', 'fileExtension': '.vsdx'},
        '.vsd': {'name': 'Microsoft Visio', 'mimeType': 'application/vnd.visio', 'fileExtension': '.vsd'},
        '.vcx': {'name': 'VirtualCatalog', 'mimeType': 'application/vnd.vcx', 'fileExtension': '.vcx'},
        '.uoml': {'name': 'Unique Object Markup Language', 'mimeType': 'application/vnd.uoml+xml', 'fileExtension': '.uoml'},
        '.unityweb': {'name': 'Unity 3d', 'mimeType': 'application/vnd.unity', 'fileExtension': '.unityweb'},
        '.umj': {'name': 'UMAJIN', 'mimeType': 'application/vnd.umajin', 'fileExtension': '.umj'},
        '.utz': {'name': 'User Interface Quartz - Theme (Symbian)', 'mimeType': 'application/vnd.uiq.theme', 'fileExtension': '.utz'},
        '.ufd': {'name': 'Universal Forms Description Language', 'mimeType': 'application/vnd.ufdl', 'fileExtension': '.ufd'},
        '.tra': {'name': 'True BASIC', 'mimeType': 'application/vnd.trueapp', 'fileExtension': '.tra'},
        '.mxs': {'name': 'Triscape Map Explorer', 'mimeType': 'application/vnd.triscape.mxs', 'fileExtension': '.mxs'},
        '.tpt': {'name': 'TRI Systems Config', 'mimeType': 'application/vnd.trid.tpt', 'fileExtension': '.tpt'},
        '.tmo': {'name': 'MobileTV', 'mimeType': 'application/vnd.tmobile-livetv', 'fileExtension': '.tmo'},
        '.tao': {'name': 'Tao Intent', 'mimeType': 'application/vnd.tao.intent-module-archive', 'fileExtension': '.tao'},
        '.xdm': {'name': 'SyncML - Device Management', 'mimeType': 'application/vnd.syncml.dm+xml', 'fileExtension': '.xdm'},
        '.bdm': {'name': 'SyncML - Device Management', 'mimeType': 'application/vnd.syncml.dm+wbxml', 'fileExtension': '.bdm'},
        '.xsm': {'name': 'SyncML', 'mimeType': 'application/vnd.syncml+xml', 'fileExtension': '.xsm'},
        '.sis': {'name': 'Symbian Install Package', 'mimeType': 'application/vnd.symbian.install', 'fileExtension': '.sis'},
        '.svd': {'name': 'SourceView Document', 'mimeType': 'application/vnd.svd', 'fileExtension': '.svd'},
        '.sus': {'name': 'ScheduleUs', 'mimeType': 'application/vnd.sus-calendar', 'fileExtension': '.sus'},
        '.stw': {'name': 'OpenOffice - Writer Template (Text - HTML)', 'mimeType': 'application/vnd.sun.xml.writer.template', 'fileExtension': '.stw'},
        '.sxg': {'name': 'OpenOffice - Writer (Text - HTML)', 'mimeType': 'application/vnd.sun.xml.writer.global', 'fileExtension': '.sxg'},
        '.sxw': {'name': 'OpenOffice - Writer (Text - HTML)', 'mimeType': 'application/vnd.sun.xml.writer', 'fileExtension': '.sxw'},
        '.sxm': {'name': 'OpenOffice - Math (Formula)', 'mimeType': 'application/vnd.sun.xml.math', 'fileExtension': '.sxm'},
        '.sti': {'name': 'OpenOffice - Impress Template (Presentation)', 'mimeType': 'application/vnd.sun.xml.impress.template', 'fileExtension': '.sti'},
        '.sxi': {'name': 'OpenOffice - Impress (Presentation)', 'mimeType': 'application/vnd.sun.xml.impress', 'fileExtension': '.sxi'},
        '.std': {'name': 'OpenOffice - Draw Template (Graphics)', 'mimeType': 'application/vnd.sun.xml.draw.template', 'fileExtension': '.std'},
        '.sxd': {'name': 'OpenOffice - Draw (Graphics)', 'mimeType': 'application/vnd.sun.xml.draw', 'fileExtension': '.sxd'},
        '.stc': {'name': 'OpenOffice - Calc Template (Spreadsheet)', 'mimeType': 'application/vnd.sun.xml.calc.template', 'fileExtension': '.stc'},
        '.sxc': {'name': 'OpenOffice - Calc (Spreadsheet)', 'mimeType': 'application/vnd.sun.xml.calc', 'fileExtension': '.sxc'},
        '.sm': {'name': 'StepMania', 'mimeType': 'application/vnd.stepmania.stepchart', 'fileExtension': '.sm'},
        '.sgl': {'name': 'StarOffice - Writer  (Global)', 'mimeType': 'application/vnd.stardivision.writer-global', 'fileExtension': '.sgl'},
        '.sdw': {'name': 'StarOffice - Writer', 'mimeType': 'application/vnd.stardivision.writer', 'fileExtension': '.sdw'},
        '.smf': {'name': 'StarOffice - Math', 'mimeType': 'application/vnd.stardivision.math', 'fileExtension': '.smf'},
        '.sdd': {'name': 'StarOffice - Impress', 'mimeType': 'application/vnd.stardivision.impress', 'fileExtension': '.sdd'},
        '.sda': {'name': 'StarOffice - Draw', 'mimeType': 'application/vnd.stardivision.draw', 'fileExtension': '.sda'},
        '.sdc': {'name': 'StarOffice - Calc', 'mimeType': 'application/vnd.stardivision.calc', 'fileExtension': '.sdc'},
        '.sfs': {'name': 'TIBCO Spotfire', 'mimeType': 'application/vnd.spotfire.sfs', 'fileExtension': '.sfs'},
        '.dxp': {'name': 'TIBCO Spotfire', 'mimeType': 'application/vnd.spotfire.dxp', 'fileExtension': '.dxp'},
        '.sdkm': {'name': 'SudokuMagic', 'mimeType': 'application/vnd.solent.sdkm+xml', 'fileExtension': '.sdkm'},
        '.teacher': {'name': 'SMART Technologies Apps', 'mimeType': 'application/vnd.smart.teacher', 'fileExtension': '.teacher'},
        '.mmf': {'name': 'SMAF File', 'mimeType': 'application/vnd.smaf', 'fileExtension': '.mmf'},
        '.twd': {'name': 'SimTech MindMapper', 'mimeType': 'application/vnd.simtech-mindmapper', 'fileExtension': '.twd'},
        '.ipk': {'name': 'Shana Informed Filler', 'mimeType': 'application/vnd.shana.informed.package', 'fileExtension': '.ipk'},
        '.iif': {'name': 'Shana Informed Filler', 'mimeType': 'application/vnd.shana.informed.interchange', 'fileExtension': '.iif'},
        '.itp': {'name': 'Shana Informed Filler', 'mimeType': 'application/vnd.shana.informed.formtemplate', 'fileExtension': '.itp'},
        '.ifm': {'name': 'Shana Informed Filler', 'mimeType': 'application/vnd.shana.informed.formdata', 'fileExtension': '.ifm'},
        '.semf': {'name': 'Secured eMail', 'mimeType': 'application/vnd.semf', 'fileExtension': '.semf'},
        '.semd': {'name': 'Secured eMail', 'mimeType': 'application/vnd.semd', 'fileExtension': '.semd'},
        '.sema': {'name': 'Secured eMail', 'mimeType': 'application/vnd.sema', 'fileExtension': '.sema'},
        '.see': {'name': 'SeeMail', 'mimeType': 'application/vnd.seemail', 'fileExtension': '.see'},
        '.st': {'name': 'SailingTracker', 'mimeType': 'application/vnd.sailingtracker.track', 'fileExtension': '.st'},
        '.link66': {'name': 'ROUTE 66 Location Based Services', 'mimeType': 'application/vnd.route66.link66+xml', 'fileExtension': '.link66'},
        '.rm': {'name': 'RealMedia', 'mimeType': 'application/vnd.rn-realmedia', 'fileExtension': '.rm'},
        '.cod': {'name': 'Blackberry COD File', 'mimeType': 'application/vnd.rim.cod', 'fileExtension': '.cod'},
        '.cryptonote': {'name': 'CryptoNote', 'mimeType': 'application/vnd.rig.cryptonote', 'fileExtension': '.cryptonote'},
        '.musicxml': {'name': 'Recordare Applications', 'mimeType': 'application/vnd.recordare.musicxml+xml', 'fileExtension': '.musicxml'},
        '.mxl': {'name': 'Recordare Applications', 'mimeType': 'application/vnd.recordare.musicxml', 'fileExtension': '.mxl'},
        '.bed': {'name': 'RealVNC', 'mimeType': 'application/vnd.realvnc.bed', 'fileExtension': '.bed'},
        '.qxd': {'name': 'QuarkXpress', 'mimeType': 'application/vnd.quark.quarkxpress', 'fileExtension': '.qxd'},
        '.ptid': {'name': 'Princeton Video Image', 'mimeType': 'application/vnd.pvi.ptid1', 'fileExtension': '.ptid'},
        '.qps': {'name': 'PubliShare Objects', 'mimeType': 'application/vnd.publishare-delta-tree', 'fileExtension': '.qps'},
        '.mgz': {'name': 'EFI Proteus', 'mimeType': 'application/vnd.proteus.magazine', 'fileExtension': '.mgz'},
        '.box': {'name': 'Preview Systems ZipLock/VBox', 'mimeType': 'application/vnd.previewsystems.box', 'fileExtension': '.box'},
        '.pbd': {'name': 'PowerBuilder', 'mimeType': 'application/vnd.powerbuilder6', 'fileExtension': '.pbd'},
        '.plf': {'name': 'PocketLearn Viewers', 'mimeType': 'application/vnd.pocketlearn', 'fileExtension': '.plf'},
        '.wg': {'name': "Qualcomm's Plaza Mobile Internet", 'mimeType': 'application/vnd.pmi.widget', 'fileExtension': '.wg'},
        '.efif': {'name': 'Pcsel eFIF File', 'mimeType': 'application/vnd.picsel', 'fileExtension': '.efif'},
        '.ei6': {'name': 'Proprietary P&amp;G Standard Reporting System', 'mimeType': 'application/vnd.pg.osasli', 'fileExtension': '.ei6'},
        '.str': {'name': 'Proprietary P&amp;G Standard Reporting System', 'mimeType': 'application/vnd.pg.format', 'fileExtension': '.str'},
        '.paw': {'name': 'PawaaFILE', 'mimeType': 'application/vnd.pawaafile', 'fileExtension': '.paw'},
        '.pdb': {'name': 'PalmOS Data', 'mimeType': 'application/vnd.palm', 'fileExtension': '.pdb'},
        '.dp': {'name': 'OSGi Deployment Package', 'mimeType': 'application/vnd.osgi.dp', 'fileExtension': '.dp'},
        '.mgp': {'name': 'MapGuide DBXML', 'mimeType': 'application/vnd.osgeo.mapguide.package', 'fileExtension': '.mgp'},
        '.dotx': {'name': 'Microsoft Office - OOXML - Word Document Template', 'mimeType': 'application/vnd.openxmlformats-officedocument.wordprocessingml.template', 'fileExtension': '.dotx'},
        '.docx': {'name': 'Microsoft Office - OOXML - Word Document', 'mimeType': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'fileExtension': '.docx'},
        '.xltx': {'name': 'Microsoft Office - OOXML - Spreadsheet Template', 'mimeType': 'application/vnd.openxmlformats-officedocument.spreadsheetml.template', 'fileExtension': '.xltx'},
        '.xlsx': {'name': 'Microsoft Office - OOXML - Spreadsheet', 'mimeType': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'fileExtension': '.xlsx'},
        '.potx': {'name': 'Microsoft Office - OOXML - Presentation Template', 'mimeType': 'application/vnd.openxmlformats-officedocument.presentationml.template', 'fileExtension': '.potx'},
        '.ppsx': {'name': 'Microsoft Office - OOXML - Presentation (Slideshow)', 'mimeType': 'application/vnd.openxmlformats-officedocument.presentationml.slideshow', 'fileExtension': '.ppsx'},
        '.sldx': {'name': 'Microsoft Office - OOXML - Presentation (Slide)', 'mimeType': 'application/vnd.openxmlformats-officedocument.presentationml.slide', 'fileExtension': '.sldx'},
        '.pptx': {'name': 'Microsoft Office - OOXML - Presentation', 'mimeType': 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'fileExtension': '.pptx'},
        '.oxt': {'name': 'Open Office Extension', 'mimeType': 'application/vnd.openofficeorg.extension', 'fileExtension': '.oxt'},
        '.dd2': {'name': 'OMA Download Agents', 'mimeType': 'application/vnd.oma.dd2+xml', 'fileExtension': '.dd2'},
        '.xo': {'name': 'Sugar Linux Application Bundle', 'mimeType': 'application/vnd.olpc-sugar', 'fileExtension': '.xo'},
        '.oth': {'name': 'Open Document Text Web', 'mimeType': 'application/vnd.oasis.opendocument.text-web', 'fileExtension': '.oth'},
        '.ott': {'name': 'OpenDocument Text Template', 'mimeType': 'application/vnd.oasis.opendocument.text-template', 'fileExtension': '.ott'},
        '.odm': {'name': 'OpenDocument Text Master', 'mimeType': 'application/vnd.oasis.opendocument.text-master', 'fileExtension': '.odm'},
        '.odt': {'name': 'OpenDocument Text', 'mimeType': 'application/vnd.oasis.opendocument.text', 'fileExtension': '.odt'},
        '.ots': {'name': 'OpenDocument Spreadsheet Template', 'mimeType': 'application/vnd.oasis.opendocument.spreadsheet-template', 'fileExtension': '.ots'},
        '.ods': {'name': 'OpenDocument Spreadsheet', 'mimeType': 'application/vnd.oasis.opendocument.spreadsheet', 'fileExtension': '.ods'},
        '.otp': {'name': 'OpenDocument Presentation Template', 'mimeType': 'application/vnd.oasis.opendocument.presentation-template', 'fileExtension': '.otp'},
        '.odp': {'name': 'OpenDocument Presentation', 'mimeType': 'application/vnd.oasis.opendocument.presentation', 'fileExtension': '.odp'},
        '.oti': {'name': 'OpenDocument Image Template', 'mimeType': 'application/vnd.oasis.opendocument.image-template', 'fileExtension': '.oti'},
        '.odi': {'name': 'OpenDocument Image', 'mimeType': 'application/vnd.oasis.opendocument.image', 'fileExtension': '.odi'},
        '.otg': {'name': 'OpenDocument Graphics Template', 'mimeType': 'application/vnd.oasis.opendocument.graphics-template', 'fileExtension': '.otg'},
        '.odg': {'name': 'OpenDocument Graphics', 'mimeType': 'application/vnd.oasis.opendocument.graphics', 'fileExtension': '.odg'},
        '.odft': {'name': 'OpenDocument Formula Template', 'mimeType': 'application/vnd.oasis.opendocument.formula-template', 'fileExtension': '.odft'},
        '.odf': {'name': 'OpenDocument Formula', 'mimeType': 'application/vnd.oasis.opendocument.formula', 'fileExtension': '.odf'},
        '.odb': {'name': 'OpenDocument Database', 'mimeType': 'application/vnd.oasis.opendocument.database', 'fileExtension': '.odb'},
        '.otc': {'name': 'OpenDocument Chart Template', 'mimeType': 'application/vnd.oasis.opendocument.chart-template', 'fileExtension': '.otc'},
        '.odc': {'name': 'OpenDocument Chart', 'mimeType': 'application/vnd.oasis.opendocument.chart', 'fileExtension': '.odc'},
        '.ext': {'name': "Novadigm's RADIA and EDM products", 'mimeType': 'application/vnd.novadigm.ext', 'fileExtension': '.ext'},
        '.edx': {'name': "Novadigm's RADIA and EDM products", 'mimeType': 'application/vnd.novadigm.edx', 'fileExtension': '.edx'},
        '.edm': {'name': "Novadigm's RADIA and EDM products", 'mimeType': 'application/vnd.novadigm.edm', 'fileExtension': '.edm'},
        '.rpss': {'name': 'Nokia Radio Application - Preset', 'mimeType': 'application/vnd.nokia.radio-presets', 'fileExtension': '.rpss'},
        '.rpst': {'name': 'Nokia Radio Application - Preset', 'mimeType': 'application/vnd.nokia.radio-preset', 'fileExtension': '.rpst'},
        '.n-gage': {'name': 'N-Gage Game Installer', 'mimeType': 'application/vnd.nokia.n-gage.symbian.install', 'fileExtension': '.n-gage'},
        '.ngdat': {'name': 'N-Gage Game Data', 'mimeType': 'application/vnd.nokia.n-gage.data', 'fileExtension': '.ngdat'},
        '.nnw': {'name': 'NobleNet Web', 'mimeType': 'application/vnd.noblenet-web', 'fileExtension': '.nnw'},
        '.nns': {'name': 'NobleNet Sealer', 'mimeType': 'application/vnd.noblenet-sealer', 'fileExtension': '.nns'},
        '.nnd': {'name': 'NobleNet Directory', 'mimeType': 'application/vnd.noblenet-directory', 'fileExtension': '.nnd'},
        '.nlu': {'name': 'neuroLanguage', 'mimeType': 'application/vnd.neurolanguage.nlu', 'fileExtension': '.nlu'},
        '.msty': {'name': 'Muvee Automatic Video Editing', 'mimeType': 'application/vnd.muvee.style', 'fileExtension': '.msty'},
        '.mus': {'name': 'MUsical Score Interpreted Code Invented  for the ASCII designation of Notation', 'mimeType': 'application/vnd.musician', 'fileExtension': '.mus'},
        '.mseq': {'name': '3GPP MSEQ File', 'mimeType': 'application/vnd.mseq', 'fileExtension': '.mseq'},
        '.xps': {'name': 'Microsoft XML Paper Specification', 'mimeType': 'application/vnd.ms-xpsdocument', 'fileExtension': '.xps'},
        '.wpl': {'name': 'Microsoft Windows Media Player Playlist', 'mimeType': 'application/vnd.ms-wpl', 'fileExtension': '.wpl'},
        '.wps': {'name': 'Microsoft Works', 'mimeType': 'application/vnd.ms-works', 'fileExtension': '.wps'},
        '.dotm': {'name': 'Microsoft Word - Macro-Enabled Template', 'mimeType': 'application/vnd.ms-word.template.macroenabled.12', 'fileExtension': '.dotm'},
        '.docm': {'name': 'Microsoft Word - Macro-Enabled Document', 'mimeType': 'application/vnd.ms-word.document.macroenabled.12', 'fileExtension': '.docm'},
        '.mpp': {'name': 'Microsoft Project', 'mimeType': 'application/vnd.ms-project', 'fileExtension': '.mpp'},
        '.potm': {'name': 'Microsoft PowerPoint - Macro-Enabled Template File', 'mimeType': 'application/vnd.ms-powerpoint.template.macroenabled.12', 'fileExtension': '.potm'},
        '.ppsm': {'name': 'Microsoft PowerPoint - Macro-Enabled Slide Show File', 'mimeType': 'application/vnd.ms-powerpoint.slideshow.macroenabled.12', 'fileExtension': '.ppsm'},
        '.sldm': {'name': 'Microsoft PowerPoint - Macro-Enabled Open XML Slide', 'mimeType': 'application/vnd.ms-powerpoint.slide.macroenabled.12', 'fileExtension': '.sldm'},
        '.pptm': {'name': 'Microsoft PowerPoint - Macro-Enabled Presentation File', 'mimeType': 'application/vnd.ms-powerpoint.presentation.macroenabled.12', 'fileExtension': '.pptm'},
        '.ppam': {'name': 'Microsoft PowerPoint - Add-in file', 'mimeType': 'application/vnd.ms-powerpoint.addin.macroenabled.12', 'fileExtension': '.ppam'},
        '.ppt': {'name': 'Microsoft PowerPoint', 'mimeType': 'application/vnd.ms-powerpoint', 'fileExtension': '.ppt'},
        '.stl': {'name': 'Microsoft Trust UI Provider - Certificate Trust Link', 'mimeType': 'application/vnd.ms-pki.stl', 'fileExtension': '.stl'},
        '.cat': {'name': 'Microsoft Trust UI Provider - Security Catalog', 'mimeType': 'application/vnd.ms-pki.seccat', 'fileExtension': '.cat'},
        '.thmx': {'name': 'Microsoft Office System Release Theme', 'mimeType': 'application/vnd.ms-officetheme', 'fileExtension': '.thmx'},
        '.lrm': {'name': 'Microsoft Learning Resource Module', 'mimeType': 'application/vnd.ms-lrm', 'fileExtension': '.lrm'},
        '.ims': {'name': 'Microsoft Class Server', 'mimeType': 'application/vnd.ms-ims', 'fileExtension': '.ims'},
        '.chm': {'name': 'Microsoft Html Help File', 'mimeType': 'application/vnd.ms-htmlhelp', 'fileExtension': '.chm'},
        '.eot': {'name': 'Microsoft Embedded OpenType', 'mimeType': 'application/vnd.ms-fontobject', 'fileExtension': '.eot'},
        '.xltm': {'name': 'Microsoft Excel - Macro-Enabled Template File', 'mimeType': 'application/vnd.ms-excel.template.macroenabled.12', 'fileExtension': '.xltm'},
        '.xlsm': {'name': 'Microsoft Excel - Macro-Enabled Workbook', 'mimeType': 'application/vnd.ms-excel.sheet.macroenabled.12', 'fileExtension': '.xlsm'},
        '.xlsb': {'name': 'Microsoft Excel - Binary Workbook', 'mimeType': 'application/vnd.ms-excel.sheet.binary.macroenabled.12', 'fileExtension': '.xlsb'},
        '.xlam': {'name': 'Microsoft Excel - Add-In File', 'mimeType': 'application/vnd.ms-excel.addin.macroenabled.12', 'fileExtension': '.xlam'},
        '.xls': {'name': 'Microsoft Excel', 'mimeType': 'application/vnd.ms-excel', 'fileExtension': '.xls'},
        '.cab': {'name': 'Microsoft Cabinet File', 'mimeType': 'application/vnd.ms-cab-compressed', 'fileExtension': '.cab'},
        '.cil': {'name': 'Microsoft Artgalry', 'mimeType': 'application/vnd.ms-artgalry', 'fileExtension': '.cil'},
        '.xul': {'name': 'XUL - XML User Interface Language', 'mimeType': 'application/vnd.mozilla.xul+xml', 'fileExtension': '.xul'},
        '.mpc': {'name': 'Mophun Certificate', 'mimeType': 'application/vnd.mophun.certificate', 'fileExtension': '.mpc'},
        '.mpn': {'name': 'Mophun VM', 'mimeType': 'application/vnd.mophun.application', 'fileExtension': '.mpn'},
        '.txf': {'name': 'Mobius Management Systems - Topic Index File', 'mimeType': 'application/vnd.mobius.txf', 'fileExtension': '.txf'},
        '.plc': {'name': 'Mobius Management Systems - Policy Definition Language File', 'mimeType': 'application/vnd.mobius.plc', 'fileExtension': '.plc'},
        '.msl': {'name': 'Mobius Management Systems - Script Language', 'mimeType': 'application/vnd.mobius.msl', 'fileExtension': '.msl'},
        '.mqy': {'name': 'Mobius Management Systems - Query File', 'mimeType': 'application/vnd.mobius.mqy', 'fileExtension': '.mqy'},
        '.mbk': {'name': 'Mobius Management Systems - Basket file', 'mimeType': 'application/vnd.mobius.mbk', 'fileExtension': '.mbk'},
        '.dis': {'name': 'Mobius Management Systems - Distribution Database', 'mimeType': 'application/vnd.mobius.dis', 'fileExtension': '.dis'},
        '.daf': {'name': 'Mobius Management Systems - UniversalArchive', 'mimeType': 'application/vnd.mobius.daf', 'fileExtension': '.daf'},
        '.mif': {'name': 'FrameMaker Interchange Format', 'mimeType': 'application/vnd.mif', 'fileExtension': '.mif'},
        '.igx': {'name': 'Micrografx iGrafx Professional', 'mimeType': 'application/vnd.micrografx.igx', 'fileExtension': '.igx'},
        '.flo': {'name': 'Micrografx', 'mimeType': 'application/vnd.micrografx.flo', 'fileExtension': '.flo'},
        '.mfm': {'name': 'Melody Format for Mobile Platform', 'mimeType': 'application/vnd.mfmp', 'fileExtension': '.mfm'},
        '.mwf': {'name': 'Medical Waveform Encoding Format', 'mimeType': 'application/vnd.mfer', 'fileExtension': '.mwf'},
        '.cdkey': {'name': 'MediaRemote', 'mimeType': 'application/vnd.mediastation.cdkey', 'fileExtension': '.cdkey'},
        '.mc1': {'name': 'MedCalc', 'mimeType': 'application/vnd.medcalcdata', 'fileExtension': '.mc1'},
        '.mcd': {'name': 'Micro CADAM Helix D&amp;D', 'mimeType': 'application/vnd.mcd', 'fileExtension': '.mcd'},
        '.portpkg': {'name': 'MacPorts Port System', 'mimeType': 'application/vnd.macports.portpkg', 'fileExtension': '.portpkg'},
        '.lwp': {'name': 'Lotus Wordpro', 'mimeType': 'application/vnd.lotus-wordpro', 'fileExtension': '.lwp'},
        '.scm': {'name': 'Lotus Screencam', 'mimeType': 'application/vnd.lotus-screencam', 'fileExtension': '.scm'},
        '.org': {'name': 'Lotus Organizer', 'mimeType': 'application/vnd.lotus-organizer', 'fileExtension': '.org'},
        '.nsf': {'name': 'Lotus Notes', 'mimeType': 'application/vnd.lotus-notes', 'fileExtension': '.nsf'},
        '.pre': {'name': 'Lotus Freelance', 'mimeType': 'application/vnd.lotus-freelance', 'fileExtension': '.pre'},
        '.apr': {'name': 'Lotus Approach', 'mimeType': 'application/vnd.lotus-approach', 'fileExtension': '.apr'},
        '.123': {'name': 'Lotus 1-2-3', 'mimeType': 'application/vnd.lotus-1-2-3', 'fileExtension': '.123'},
        '.lbe': {'name': 'Life Balance - Exchange Format', 'mimeType': 'application/vnd.llamagraphics.life-balance.exchange+xml', 'fileExtension': '.lbe'},
        '.lbd': {'name': 'Life Balance - Desktop Edition', 'mimeType': 'application/vnd.llamagraphics.life-balance.desktop', 'fileExtension': '.lbd'},
        '.lasxml': {'name': 'Laser App Enterprise', 'mimeType': 'application/vnd.las.las+xml', 'fileExtension': '.lasxml'},
        '.sse': {'name': 'Kodak Storyshare', 'mimeType': 'application/vnd.kodak-descriptor', 'fileExtension': '.sse'},
        '.skp': {'name': 'SSEYO Koan Play File', 'mimeType': 'application/vnd.koan', 'fileExtension': '.skp'},
        '.kne': {'name': 'Kinar Applications', 'mimeType': 'application/vnd.kinar', 'fileExtension': '.kne'},
        '.kia': {'name': 'Kidspiration', 'mimeType': 'application/vnd.kidspiration', 'fileExtension': '.kia'},
        '.htke': {'name': 'Kenamea App', 'mimeType': 'application/vnd.kenameaapp', 'fileExtension': '.htke'},
        '.kwd': {'name': 'KDE KOffice Office Suite - Kword', 'mimeType': 'application/vnd.kde.kword', 'fileExtension': '.kwd'},
        '.ksp': {'name': 'KDE KOffice Office Suite - Kspread', 'mimeType': 'application/vnd.kde.kspread', 'fileExtension': '.ksp'},
        '.kpr': {'name': 'KDE KOffice Office Suite - Kpresenter', 'mimeType': 'application/vnd.kde.kpresenter', 'fileExtension': '.kpr'},
        '.kon': {'name': 'KDE KOffice Office Suite - Kontour', 'mimeType': 'application/vnd.kde.kontour', 'fileExtension': '.kon'},
        '.flw': {'name': 'KDE KOffice Office Suite - Kivio', 'mimeType': 'application/vnd.kde.kivio', 'fileExtension': '.flw'},
        '.kfo': {'name': 'KDE KOffice Office Suite - Kformula', 'mimeType': 'application/vnd.kde.kformula', 'fileExtension': '.kfo'},
        '.chrt': {'name': 'KDE KOffice Office Suite - KChart', 'mimeType': 'application/vnd.kde.kchart', 'fileExtension': '.chrt'},
        '.karbon': {'name': 'KDE KOffice Office Suite - Karbon', 'mimeType': 'application/vnd.kde.karbon', 'fileExtension': '.karbon'},
        '.ktz': {'name': 'Kahootz', 'mimeType': 'application/vnd.kahootz', 'fileExtension': '.ktz'},
        '.joda': {'name': 'Joda Archive', 'mimeType': 'application/vnd.joost.joda-archive', 'fileExtension': '.joda'},
        '.jisp': {'name': 'RhymBox', 'mimeType': 'application/vnd.jisp', 'fileExtension': '.jisp'},
        '.rms': {'name': 'Mobile Information Device Profile', 'mimeType': 'application/vnd.jcp.javame.midlet-rms', 'fileExtension': '.rms'},
        '.jam': {'name': 'Lightspeed Audio Lab', 'mimeType': 'application/vnd.jam', 'fileExtension': '.jam'},
        '.fcs': {'name': 'International Society for Advancement of Cytometry', 'mimeType': 'application/vnd.isac.fcs', 'fileExtension': '.fcs'},
        '.xpr': {'name': 'Express by Infoseek', 'mimeType': 'application/vnd.is-xpr', 'fileExtension': '.xpr'},
        '.irp': {'name': 'iRepository / Lucidoc Editor', 'mimeType': 'application/vnd.irepository.package+xml', 'fileExtension': '.irp'},
        '.rcprofile': {'name': 'IP Unplugged Roaming Client', 'mimeType': 'application/vnd.ipunplugged.rcprofile', 'fileExtension': '.rcprofile'},
        '.qfx': {'name': 'Quicken', 'mimeType': 'application/vnd.intu.qfx', 'fileExtension': '.qfx'},
        '.qbo': {'name': 'Open Financial Exchange', 'mimeType': 'application/vnd.intu.qbo', 'fileExtension': '.qbo'},
        '.i2g': {'name': 'Interactive Geometry Software', 'mimeType': 'application/vnd.intergeo', 'fileExtension': '.i2g'},
        '.xpw': {'name': 'Intercon FormNet', 'mimeType': 'application/vnd.intercon.formnet', 'fileExtension': '.xpw'},
        '.igm': {'name': 'IOCOM Visimeet', 'mimeType': 'application/vnd.insors.igm', 'fileExtension': '.igm'},
        '.ivu': {'name': 'ImmerVision PURE Players', 'mimeType': 'application/vnd.immervision-ivu', 'fileExtension': '.ivu'},
        '.ivp': {'name': 'ImmerVision PURE Players', 'mimeType': 'application/vnd.immervision-ivp', 'fileExtension': '.ivp'},
        '.igl': {'name': 'igLoader', 'mimeType': 'application/vnd.igloader', 'fileExtension': '.igl'},
        '.icc': {'name': 'ICC profile', 'mimeType': 'application/vnd.iccprofile', 'fileExtension': '.icc'},
        '.sc': {'name': 'IBM Electronic Media Management System - Secure Container', 'mimeType': 'application/vnd.ibm.secure-container', 'fileExtension': '.sc'},
        '.irm': {'name': 'IBM DB2 Rights Manager', 'mimeType': 'application/vnd.ibm.rights-management', 'fileExtension': '.irm'},
        '.afp': {'name': 'MO:DCA-P', 'mimeType': 'application/vnd.ibm.modcap', 'fileExtension': '.afp'},
        '.mpy': {'name': 'MiniPay', 'mimeType': 'application/vnd.ibm.minipay', 'fileExtension': '.mpy'},
        '.x3d': {'name': '3D Crossword Plugin', 'mimeType': 'application/vnd.hzn-3d-crossword', 'fileExtension': '.x3d'},
        '.sfd-hdstx': {'name': 'Hydrostatix Master Suite', 'mimeType': 'application/vnd.hydrostatix.sof-data', 'fileExtension': '.sfd-hdstx'},
        '.pclxl': {'name': 'PCL 6 Enhanced (Formely PCL XL)', 'mimeType': 'application/vnd.hp-pclxl', 'fileExtension': '.pclxl'},
        '.pcl': {'name': 'HP Printer Command Language', 'mimeType': 'application/vnd.hp-pcl', 'fileExtension': '.pcl'},
        '.jlt': {'name': 'HP Indigo Digital Press - Job Layout Languate', 'mimeType': 'application/vnd.hp-jlyt', 'fileExtension': '.jlt'},
        '.hps': {'name': "Hewlett-Packard's WebPrintSmart", 'mimeType': 'application/vnd.hp-hps', 'fileExtension': '.hps'},
        '.hpid': {'name': 'Hewlett Packard Instant Delivery', 'mimeType': 'application/vnd.hp-hpid', 'fileExtension': '.hpid'},
        '.hpgl': {'name': 'HP-GL/2 and HP RTL', 'mimeType': 'application/vnd.hp-hpgl', 'fileExtension': '.hpgl'},
        '.les': {'name': 'Archipelago Lesson Player', 'mimeType': 'application/vnd.hhe.lesson-player', 'fileExtension': '.les'},
        '.hbci': {'name': 'Homebanking Computer Interface (HBCI)', 'mimeType': 'application/vnd.hbci', 'fileExtension': '.hbci'},
        '.zmm': {'name': 'ZVUE Media Manager', 'mimeType': 'application/vnd.handheld-entertainment+xml', 'fileExtension': '.zmm'},
        '.hal': {'name': 'Hypertext Application Language', 'mimeType': 'application/vnd.hal+xml', 'fileExtension': '.hal'},
        '.vcg': {'name': 'Groove - Vcard', 'mimeType': 'application/vnd.groove-vcard', 'fileExtension': '.vcg'},
        '.tpl': {'name': 'Groove - Tool Template', 'mimeType': 'application/vnd.groove-tool-template', 'fileExtension': '.tpl'},
        '.gtm': {'name': 'Groove - Tool Message', 'mimeType': 'application/vnd.groove-tool-message', 'fileExtension': '.gtm'},
        '.grv': {'name': 'Groove - Injector', 'mimeType': 'application/vnd.groove-injector', 'fileExtension': '.grv'},
        '.gim': {'name': 'Groove - Identity Message', 'mimeType': 'application/vnd.groove-identity-message', 'fileExtension': '.gim'},
        '.ghf': {'name': 'Groove - Help', 'mimeType': 'application/vnd.groove-help', 'fileExtension': '.ghf'},
        '.gac': {'name': 'Groove - Account', 'mimeType': 'application/vnd.groove-account', 'fileExtension': '.gac'},
        '.gqf': {'name': 'GrafEq', 'mimeType': 'application/vnd.grafeq', 'fileExtension': '.gqf'},
        '.kmz': {'name': 'Google Earth - Zipped KML', 'mimeType': 'application/vnd.google-earth.kmz', 'fileExtension': '.kmz'},
        '.kml': {'name': 'Google Earth - KML', 'mimeType': 'application/vnd.google-earth.kml+xml', 'fileExtension': '.kml'},
        '.gmx': {'name': 'GameMaker ActiveX', 'mimeType': 'application/vnd.gmx', 'fileExtension': '.gmx'},
        '.g3w': {'name': 'GeospacW', 'mimeType': 'application/vnd.geospace', 'fileExtension': '.g3w'},
        '.g2w': {'name': 'GeoplanW', 'mimeType': 'application/vnd.geoplan', 'fileExtension': '.g2w'},
        '.gxt': {'name': 'GEONExT and JSXGraph', 'mimeType': 'application/vnd.geonext', 'fileExtension': '.gxt'},
        '.gex': {'name': 'GeoMetry Explorer', 'mimeType': 'application/vnd.geometry-explorer', 'fileExtension': '.gex'},
        '.ggt': {'name': 'GeoGebra', 'mimeType': 'application/vnd.geogebra.tool', 'fileExtension': '.ggt'},
        '.ggb': {'name': 'GeoGebra', 'mimeType': 'application/vnd.geogebra.file', 'fileExtension': '.ggb'},
        '.txd': {'name': 'Genomatix Tuxedo Framework', 'mimeType': 'application/vnd.genomatix.tuxedo', 'fileExtension': '.txd'},
        '.fzs': {'name': 'FuzzySheet', 'mimeType': 'application/vnd.fuzzysheet', 'fileExtension': '.fzs'},
        '.xbd': {'name': 'Fujitsu - Xerox DocuWorks Binder', 'mimeType': 'application/vnd.fujixerox.docuworks.binder', 'fileExtension': '.xbd'},
        '.xdw': {'name': 'Fujitsu - Xerox DocuWorks', 'mimeType': 'application/vnd.fujixerox.docuworks', 'fileExtension': '.xdw'},
        '.ddd': {'name': 'Fujitsu - Xerox 2D CAD Data', 'mimeType': 'application/vnd.fujixerox.ddd', 'fileExtension': '.ddd'},
        '.bh2': {'name': 'Fujitsu Oasys', 'mimeType': 'application/vnd.fujitsu.oasysprs', 'fileExtension': '.bh2'},
        '.fg5': {'name': 'Fujitsu Oasys', 'mimeType': 'application/vnd.fujitsu.oasysgp', 'fileExtension': '.fg5'},
        '.oa3': {'name': 'Fujitsu Oasys', 'mimeType': 'application/vnd.fujitsu.oasys3', 'fileExtension': '.oa3'},
        '.oa2': {'name': 'Fujitsu Oasys', 'mimeType': 'application/vnd.fujitsu.oasys2', 'fileExtension': '.oa2'},
        '.oas': {'name': 'Fujitsu Oasys', 'mimeType': 'application/vnd.fujitsu.oasys', 'fileExtension': '.oas'},
        '.fsc': {'name': 'Friendly Software Corporation', 'mimeType': 'application/vnd.fsc.weblaunch', 'fileExtension': '.fsc'},
        '.ltf': {'name': 'Frogans Player', 'mimeType': 'application/vnd.frogans.ltf', 'fileExtension': '.ltf'},
        '.fnc': {'name': 'Frogans Player', 'mimeType': 'application/vnd.frogans.fnc', 'fileExtension': '.fnc'},
        '.fm': {'name': 'FrameMaker Normal Format', 'mimeType': 'application/vnd.framemaker', 'fileExtension': '.fm'},
        '.ftc': {'name': 'FluxTime Clip', 'mimeType': 'application/vnd.fluxtime.clip', 'fileExtension': '.ftc'},
        '.gph': {'name': 'NpGraphIt', 'mimeType': 'application/vnd.flographit', 'fileExtension': '.gph'},
        '.seed': {'name': 'Digital Siesmograph Networks - SEED Datafiles', 'mimeType': 'application/vnd.fdsn.seed', 'fileExtension': '.seed'},
        '.fdf': {'name': 'Forms Data Format', 'mimeType': 'application/vnd.fdf', 'fileExtension': '.fdf'},
        '.ez3': {'name': 'EZPix Secure Photo Album', 'mimeType': 'application/vnd.ezpix-package', 'fileExtension': '.ez3'},
        '.ez2': {'name': 'EZPix Secure Photo Album', 'mimeType': 'application/vnd.ezpix-album', 'fileExtension': '.ez2'},
        '.es3': {'name': 'MICROSEC e-Szign¢', 'mimeType': 'application/vnd.eszigno3+xml', 'fileExtension': '.es3'},
        '.ssf': {'name': 'QUASS Stream Player', 'mimeType': 'application/vnd.epson.ssf', 'fileExtension': '.ssf'},
        '.slt': {'name': 'SimpleAnimeLite Player', 'mimeType': 'application/vnd.epson.salt', 'fileExtension': '.slt'},
        '.qam': {'name': 'QuickAnime Player', 'mimeType': 'application/vnd.epson.quickanime', 'fileExtension': '.qam'},
        '.msf': {'name': 'QUASS Stream Player', 'mimeType': 'application/vnd.epson.msf', 'fileExtension': '.msf'},
        '.esf': {'name': 'QUASS Stream Player', 'mimeType': 'application/vnd.epson.esf', 'fileExtension': '.esf'},
        '.nml': {'name': 'Enliven Viewer', 'mimeType': 'application/vnd.enliven', 'fileExtension': '.nml'},
        '.mag': {'name': 'EcoWin Chart', 'mimeType': 'application/vnd.ecowin.chart', 'fileExtension': '.mag'},
        '.geo': {'name': 'DynaGeo', 'mimeType': 'application/vnd.dynageo', 'fileExtension': '.geo'},
        '.svc': {'name': 'Digital Video Broadcasting', 'mimeType': 'application/vnd.dvb.service', 'fileExtension': '.svc'},
        '.ait': {'name': 'Digital Video Broadcasting', 'mimeType': 'application/vnd.dvb.ait', 'fileExtension': '.ait'},
        '.dfac': {'name': 'DreamFactory', 'mimeType': 'application/vnd.dreamfactory', 'fileExtension': '.dfac'},
        '.dpg': {'name': 'DPGraph', 'mimeType': 'application/vnd.dpgraph', 'fileExtension': '.dpg'},
        '.mlp': {'name': 'Dolby Meridian Lossless Packing', 'mimeType': 'application/vnd.dolby.mlp', 'fileExtension': '.mlp'},
        '.dna': {'name': 'New Moon Liftoff/DNA', 'mimeType': 'application/vnd.dna', 'fileExtension': '.dna'},
        '.fe_launch': {'name': 'FCS Express Layout Link', 'mimeType': 'application/vnd.denovo.fcselayout-link', 'fileExtension': '.fe_launch'},
        '.rdz': {'name': 'RemoteDocs R-Viewer', 'mimeType': 'application/vnd.data-vision.rdz', 'fileExtension': '.rdz'},
        '.pcurl': {'name': 'CURL Applet', 'mimeType': 'application/vnd.curl.pcurl', 'fileExtension': '.pcurl'},
        '.car': {'name': 'CURL Applet', 'mimeType': 'application/vnd.curl.car', 'fileExtension': '.car'},
        '.ppd': {'name': 'Adobe PostScript Printer Description File Format', 'mimeType': 'application/vnd.cups-ppd', 'fileExtension': '.ppd'},
        '.pml': {'name': 'PosML', 'mimeType': 'application/vnd.ctc-posml', 'fileExtension': '.pml'},
        '.wbs': {'name': 'Critical Tools - PERT Chart EXPERT', 'mimeType': 'application/vnd.criticaltools.wbs+xml', 'fileExtension': '.wbs'},
        '.clkw': {'name': 'CrickSoftware - Clicker - Wordbank', 'mimeType': 'application/vnd.crick.clicker.wordbank', 'fileExtension': '.clkw'},
        '.clkt': {'name': 'CrickSoftware - Clicker - Template', 'mimeType': 'application/vnd.crick.clicker.template', 'fileExtension': '.clkt'},
        '.clkp': {'name': 'CrickSoftware - Clicker - Palette', 'mimeType': 'application/vnd.crick.clicker.palette', 'fileExtension': '.clkp'},
        '.clkk': {'name': 'CrickSoftware - Clicker - Keyboard', 'mimeType': 'application/vnd.crick.clicker.keyboard', 'fileExtension': '.clkk'},
        '.clkx': {'name': 'CrickSoftware - Clicker', 'mimeType': 'application/vnd.crick.clicker', 'fileExtension': '.clkx'},
        '.cmc': {'name': 'CosmoCaller', 'mimeType': 'application/vnd.cosmocaller', 'fileExtension': '.cmc'},
        '.cdbcmsg': {'name': 'CIM Database', 'mimeType': 'application/vnd.contact.cmsg', 'fileExtension': '.cdbcmsg'},
        '.csp': {'name': 'Sixth Floor Media - CommonSpace', 'mimeType': 'application/vnd.commonspace', 'fileExtension': '.csp'},
        '.c11amz': {'name': 'ClueTrust CartoMobile - Config Package', 'mimeType': 'application/vnd.cluetrust.cartomobile-config-pkg', 'fileExtension': '.c11amz'},
        '.c11amc': {'name': 'ClueTrust CartoMobile - Config', 'mimeType': 'application/vnd.cluetrust.cartomobile-config', 'fileExtension': '.c11amc'},
        '.c4g': {'name': 'Clonk Game', 'mimeType': 'application/vnd.clonk.c4group', 'fileExtension': '.c4g'},
        '.rp9': {'name': 'RetroPlatform Player', 'mimeType': 'application/vnd.cloanto.rp9', 'fileExtension': '.rp9'},
        '.cla': {'name': 'Claymore Data Files', 'mimeType': 'application/vnd.claymore', 'fileExtension': '.cla'},
        '.cdy': {'name': 'Interactive Geometry Software Cinderella', 'mimeType': 'application/vnd.cinderella', 'fileExtension': '.cdy'},
        '.mmd': {'name': 'Karaoke on Chipnuts Chipsets', 'mimeType': 'application/vnd.chipnuts.karaoke-mmd', 'fileExtension': '.mmd'},
        '.cdxml': {'name': 'CambridgeSoft Chem Draw', 'mimeType': 'application/vnd.chemdraw+xml', 'fileExtension': '.cdxml'},
        '.rep': {'name': 'BusinessObjects', 'mimeType': 'application/vnd.businessobjects', 'fileExtension': '.rep'},
        '.bmi': {'name': 'BMI Drawing Data Interchange', 'mimeType': 'application/vnd.bmi', 'fileExtension': '.bmi'},
        '.mpm': {'name': 'Blueice Research Multipass', 'mimeType': 'application/vnd.blueice.multipass', 'fileExtension': '.mpm'},
        '.aep': {'name': 'Audiograph', 'mimeType': 'application/vnd.audiograph', 'fileExtension': '.aep'},
        '.swi': {'name': 'Arista Networks Software Image', 'mimeType': 'application/vnd.aristanetworks.swi', 'fileExtension': '.swi'},
        '.m3u8': {'name': 'Multimedia Playlist Unicode', 'mimeType': 'application/vnd.apple.mpegurl', 'fileExtension': '.m3u8'},
        '.mpkg': {'name': 'Apple Installer Package', 'mimeType': 'application/vnd.apple.installer+xml', 'fileExtension': '.mpkg'},
        '.atx': {'name': 'Antix Game Player', 'mimeType': 'application/vnd.antix.game-component', 'fileExtension': '.atx'},
        '.fti': {'name': 'ANSER-WEB Terminal Client - Web Funds Transfer', 'mimeType': 'application/vnd.anser-web-funds-transfer-initiation', 'fileExtension': '.fti'},
        '.cii': {'name': 'ANSER-WEB Terminal Client - Certificate Issue', 'mimeType': 'application/vnd.anser-web-certificate-issue-initiation', 'fileExtension': '.cii'},
        '.apk': {'name': 'Android Package Archive', 'mimeType': 'application/vnd.android.package-archive', 'fileExtension': '.apk'},
        '.ami': {'name': 'AmigaDE', 'mimeType': 'application/vnd.amiga.ami', 'fileExtension': '.ami'},
        '.acc': {'name': 'Active Content Compression', 'mimeType': 'application/vnd.americandynamics.acc', 'fileExtension': '.acc'},
        '.azw': {'name': 'Amazon Kindle eBook format', 'mimeType': 'application/vnd.amazon.ebook', 'fileExtension': '.azw'},
        '.azs': {'name': 'AirZip FileSECURE', 'mimeType': 'application/vnd.airzip.filesecure.azs', 'fileExtension': '.azs'},
        '.azf': {'name': 'AirZip FileSECURE', 'mimeType': 'application/vnd.airzip.filesecure.azf', 'fileExtension': '.azf'},
        '.ahead': {'name': 'Ahead AIR Application', 'mimeType': 'application/vnd.ahead.space', 'fileExtension': '.ahead'},
        '.xfdf': {'name': 'Adobe XML Forms Data Format', 'mimeType': 'application/vnd.adobe.xfdf', 'fileExtension': '.xfdf'},
        '.xdp': {'name': 'Adobe XML Data Package', 'mimeType': 'application/vnd.adobe.xdp+xml', 'fileExtension': '.xdp'},
        '.fxp': {'name': 'Adobe Flex Project', 'mimeType': 'application/vnd.adobe.fxp', 'fileExtension': '.fxp'},
        '.air': {'name': 'Adobe AIR Application', 'mimeType': 'application/vnd.adobe.air-application-installer-package+zip', 'fileExtension': '.air'},
        '.atc': {'name': 'ACU Cobol', 'mimeType': 'application/vnd.acucorp', 'fileExtension': '.atc'},
        '.acu': {'name': 'ACU Cobol', 'mimeType': 'application/vnd.acucobol', 'fileExtension': '.acu'},
        '.imp': {'name': 'Simply Accounting - Data Import', 'mimeType': 'application/vnd.accpac.simply.imp', 'fileExtension': '.imp'},
        '.aso': {'name': 'Simply Accounting', 'mimeType': 'application/vnd.accpac.simply.aso', 'fileExtension': '.aso'},
        '.pwn': {'name': '3M Post It Notes', 'mimeType': 'application/vnd.3m.post-it-notes', 'fileExtension': '.pwn'},
        '.tcap': {'name': '3rd Generation Partnership Project - Transaction Capabilities Application Part', 'mimeType': 'application/vnd.3gpp2.tcap', 'fileExtension': '.tcap'},
        '.pvb': {'name': '3rd Generation Partnership Project - Pic Var', 'mimeType': 'application/vnd.3gpp.pic-bw-var', 'fileExtension': '.pvb'},
        '.psb': {'name': '3rd Generation Partnership Project - Pic Small', 'mimeType': 'application/vnd.3gpp.pic-bw-small', 'fileExtension': '.psb'},
        '.plb': {'name': '3rd Generation Partnership Project - Pic Large', 'mimeType': 'application/vnd.3gpp.pic-bw-large', 'fileExtension': '.plb'},
        '.tsd': {'name': 'Time Stamped Data Envelope', 'mimeType': 'application/timestamped-data', 'fileExtension': '.tsd'},
        '.tfi': {'name': 'Sharing Transaction Fraud Data', 'mimeType': 'application/thraud+xml', 'fileExtension': '.tfi'},
        '.tei': {'name': 'Text Encoding and Interchange', 'mimeType': 'application/tei+xml', 'fileExtension': '.tei'},
        '.ssml': {'name': 'Speech Synthesis Markup Language', 'mimeType': 'application/ssml+xml', 'fileExtension': '.ssml'},
        '.sru': {'name': 'Search/Retrieve via URL Response Format', 'mimeType': 'application/sru+xml', 'fileExtension': '.sru'},
        '.grxml': {'name': 'Speech Recognition Grammar Specification - XML', 'mimeType': 'application/srgs+xml', 'fileExtension': '.grxml'},
        '.gram': {'name': 'Speech Recognition Grammar Specification', 'mimeType': 'application/srgs', 'fileExtension': '.gram'},
        '.srx': {'name': 'SPARQL - Results', 'mimeType': 'application/sparql-results+xml', 'fileExtension': '.srx'},
        '.rq': {'name': 'SPARQL - Query', 'mimeType': 'application/sparql-query', 'fileExtension': '.rq'},
        '.smi': {'name': 'Synchronized Multimedia Integration Language', 'mimeType': 'application/smil+xml', 'fileExtension': '.smi'},
        '.shf': {'name': 'S Hexdump Format', 'mimeType': 'application/shf+xml', 'fileExtension': '.shf'},
        '.setreg': {'name': 'Secure Electronic Transaction - Registration', 'mimeType': 'application/set-registration-initiation', 'fileExtension': '.setreg'},
        '.setpay': {'name': 'Secure Electronic Transaction - Payment', 'mimeType': 'application/set-payment-initiation', 'fileExtension': '.setpay'},
        '.sdp': {'name': 'Session Description Protocol', 'mimeType': 'application/sdp', 'fileExtension': '.sdp'},
        '.spp': {'name': 'Server-Based Certificate Validation Protocol - Validation Policies - Response', 'mimeType': 'application/scvp-vp-response', 'fileExtension': '.spp'},
        '.spq': {'name': 'Server-Based Certificate Validation Protocol - Validation Policies - Request', 'mimeType': 'application/scvp-vp-request', 'fileExtension': '.spq'},
        '.scs': {'name': 'Server-Based Certificate Validation Protocol - Validation Response', 'mimeType': 'application/scvp-cv-response', 'fileExtension': '.scs'},
        '.scq': {'name': 'Server-Based Certificate Validation Protocol - Validation Request', 'mimeType': 'application/scvp-cv-request', 'fileExtension': '.scq'},
        '.sbml': {'name': 'Systems Biology Markup Language', 'mimeType': 'application/sbml+xml', 'fileExtension': '.sbml'},
        '.rtf': {'name': 'Rich Text Format', 'mimeType': 'application/rtf', 'fileExtension': '.rtf'},
        '.rtf': {'name': 'Rich Text Format', 'mimeType': 'text/rtf', 'fileExtension': '.rtf'},
        '.rss, .xml': {'name': 'RSS - Really Simple Syndication', 'mimeType': 'application/rss+xml', 'fileExtension': '.rss, .xml'},
        '.rsd': {'name': 'Really Simple Discovery', 'mimeType': 'application/rsd+xml', 'fileExtension': '.rsd'},
        '.rs': {'name': 'XML Resource Lists', 'mimeType': 'application/rls-services+xml', 'fileExtension': '.rs'},
        '.rld': {'name': 'XML Resource Lists Diff', 'mimeType': 'application/resource-lists-diff+xml', 'fileExtension': '.rld'},
        '.rl': {'name': 'XML Resource Lists', 'mimeType': 'application/resource-lists+xml', 'fileExtension': '.rl'},
        '.rnc': {'name': 'Relax NG Compact Syntax', 'mimeType': 'application/relax-ng-compact-syntax', 'fileExtension': '.rnc'},
        '.rif': {'name': 'IMS Networks', 'mimeType': 'application/reginfo+xml', 'fileExtension': '.rif'},
        '.rdf': {'name': 'Resource Description Framework', 'mimeType': 'application/rdf+xml', 'fileExtension': '.rdf'},
        '.pskcxml': {'name': 'Portable Symmetric Key Container', 'mimeType': 'application/pskc+xml', 'fileExtension': '.pskcxml'},
        '.cww': {'name': 'CU-Writer', 'mimeType': 'application/prs.cww', 'fileExtension': '.cww'},
        '.ai': {'name': 'PostScript', 'mimeType': 'application/postscript', 'fileExtension': '.ai'},
        '.pls': {'name': 'Pronunciation Lexicon Specification', 'mimeType': 'application/pls+xml', 'fileExtension': '.pls'},
        '.pki': {'name': 'Internet Public Key Infrastructure - Certificate Management Protocole', 'mimeType': 'application/pkixcmp', 'fileExtension': '.pki'},
        '.pkipath': {'name': 'Internet Public Key Infrastructure - Certification Path', 'mimeType': 'application/pkix-pkipath', 'fileExtension': '.pkipath'},
        '.crl': {'name': 'Internet Public Key Infrastructure - Certificate Revocation Lists', 'mimeType': 'application/pkix-crl', 'fileExtension': '.crl'},
        '.cer': {'name': 'Internet Public Key Infrastructure - Certificate', 'mimeType': 'application/pkix-cert', 'fileExtension': '.cer'},
        '.ac': {'name': 'Attribute Certificate', 'mimeType': 'application/pkix-attr-cert', 'fileExtension': '.ac'},
        '.p8': {'name': 'PKCS #8 - Private-Key Information Syntax Standard', 'mimeType': 'application/pkcs8', 'fileExtension': '.p8'},
        '.p7s': {'name': 'PKCS #7 - Cryptographic Message Syntax Standard', 'mimeType': 'application/pkcs7-signature', 'fileExtension': '.p7s'},
        '.p7m': {'name': 'PKCS #7 - Cryptographic Message Syntax Standard', 'mimeType': 'application/pkcs7-mime', 'fileExtension': '.p7m'},
        '.p10': {'name': 'PKCS #10 - Certification Request Standard', 'mimeType': 'application/pkcs10', 'fileExtension': '.p10'},
        '.prf': {'name': 'PICSRules', 'mimeType': 'application/pics-rules', 'fileExtension': '.prf'},
        '.pgp': {'name': 'Pretty Good Privacy - Signature', 'mimeType': 'application/pgp-signature', 'fileExtension': '.pgp'},
        '.pgp': {'name': 'Pretty Good Privacy', 'mimeType': 'application/pgp-encrypted', 'fileExtension': '.pgp'},
        '.pdf': {'name': 'Adobe Portable Document Format', 'mimeType': 'application/pdf', 'fileExtension': '.pdf'},
        '.xer': {'name': 'XML Patch Framework', 'mimeType': 'application/patch-ops-error+xml', 'fileExtension': '.xer'},
        '.onetoc': {'name': 'Microsoft OneNote', 'mimeType': 'application/onenote', 'fileExtension': '.onetoc'},
        '.ogx': {'name': 'Ogg', 'mimeType': 'application/ogg', 'fileExtension': '.ogx'},
        '.opf': {'name': 'Open eBook Publication Structure', 'mimeType': 'application/oebps-package+xml', 'fileExtension': '.opf'},
        '.oda': {'name': 'Office Document Architecture', 'mimeType': 'application/oda', 'fileExtension': '.oda'},
        '.bin': {'name': 'Binary Data', 'mimeType': 'application/octet-stream', 'fileExtension': '.bin'},
        '.mxf': {'name': 'Material Exchange Format', 'mimeType': 'application/mxf', 'fileExtension': '.mxf'},
        '.doc': {'name': 'Microsoft Word', 'mimeType': 'application/msword', 'fileExtension': '.doc'},
        '.mp4': {'name': 'MPEG4', 'mimeType': 'application/mp4', 'fileExtension': '.mp4'},
        '.m21': {'name': 'MPEG-21', 'mimeType': 'application/mp21', 'fileExtension': '.m21'},
        '.mods': {'name': 'Metadata Object Description Schema', 'mimeType': 'application/mods+xml', 'fileExtension': '.mods'},
        '.mets': {'name': 'Metadata Encoding and Transmission Standard', 'mimeType': 'application/mets+xml', 'fileExtension': '.mets'},
        '.meta4': {'name': 'Metalink', 'mimeType': 'application/metalink4+xml', 'fileExtension': '.meta4'},
        '.mscml': {'name': 'Media Server Control Markup Language', 'mimeType': 'application/mediaservercontrol+xml', 'fileExtension': '.mscml'},
        '.mbox': {'name': 'Mbox database files', 'mimeType': 'application/mbox', 'fileExtension': '.mbox'},
        '.mathml': {'name': 'Mathematical Markup Language', 'mimeType': 'application/mathml+xml', 'fileExtension': '.mathml'},
        '.ma': {'name': 'Mathematica Notebooks', 'mimeType': 'application/mathematica', 'fileExtension': '.ma'},
        '.mrcx': {'name': 'MARC21 XML Schema', 'mimeType': 'application/marcxml+xml', 'fileExtension': '.mrcx'},
        '.mrc': {'name': 'MARC Formats', 'mimeType': 'application/marc', 'fileExtension': '.mrc'},
        '.mads': {'name': 'Metadata Authority  Description Schema', 'mimeType': 'application/mads+xml', 'fileExtension': '.mads'},
        '.cpt': {'name': 'Compact Pro', 'mimeType': 'application/mac-compactpro', 'fileExtension': '.cpt'},
        '.hqx': {'name': 'Macintosh BinHex 4.0', 'mimeType': 'application/mac-binhex40', 'fileExtension': '.hqx'},
        '.json': {'name': 'JavaScript Object Notation (JSON)', 'mimeType': 'application/json', 'fileExtension': '.json'},
        '.js': {'name': 'JavaScript', 'mimeType': 'application/javascript', 'fileExtension': '.js'},
        '.class': {'name': 'Java Bytecode File', 'mimeType': 'application/java-vm', 'fileExtension': '.class'},
        '.ser': {'name': 'Java Serialized Object', 'mimeType': 'application/java-serialized-object', 'fileExtension': '.ser'},
        '.jar': {'name': 'Java Archive', 'mimeType': 'application/java-archive', 'fileExtension': '.jar'},
        '.ipfix': {'name': 'Internet Protocol Flow Information Export', 'mimeType': 'application/ipfix', 'fileExtension': '.ipfix'},
        '.stk': {'name': 'Hyperstudio', 'mimeType': 'application/hyperstudio', 'fileExtension': '.stk'},
        '.pfr': {'name': 'Portable Font Resource', 'mimeType': 'application/font-tdpfr', 'fileExtension': '.pfr'},
        '.exi': {'name': 'Efficient XML Interchange', 'mimeType': 'application/exi', 'fileExtension': '.exi'},
        '.epub': {'name': 'Electronic Publication', 'mimeType': 'application/epub+zip', 'fileExtension': '.epub'},
        '.emma': {'name': 'Extensible MultiModal Annotation', 'mimeType': 'application/emma+xml', 'fileExtension': '.emma'},
        '.es': {'name': 'ECMAScript', 'mimeType': 'application/ecmascript', 'fileExtension': '.es'},
        '.xdssc': {'name': 'Data Structure for the Security Suitability of Cryptographic Algorithms', 'mimeType': 'application/dssc+xml', 'fileExtension': '.xdssc'},
        '.dssc': {'name': 'Data Structure for the Security Suitability of Cryptographic Algorithms', 'mimeType': 'application/dssc+der', 'fileExtension': '.dssc'},
        '.davmount': {'name': 'Web Distributed Authoring and Versioning', 'mimeType': 'application/davmount+xml', 'fileExtension': '.davmount'},
        '.cu': {'name': 'CU-SeeMe', 'mimeType': 'application/cu-seeme', 'fileExtension': '.cu'},
        '.cdmiq': {'name': 'Cloud Data Management Interface (CDMI) - Queue', 'mimeType': 'application/cdmi-queue', 'fileExtension': '.cdmiq'},
        '.cdmio': {'name': 'Cloud Data Management Interface (CDMI) - Object', 'mimeType': 'application/cdmi-object', 'fileExtension': '.cdmio'},
        '.cdmid': {'name': 'Cloud Data Management Interface (CDMI) - Domain', 'mimeType': 'application/cdmi-domain', 'fileExtension': '.cdmid'},
        '.cdmic': {'name': 'Cloud Data Management Interface (CDMI) - Contaimer', 'mimeType': 'application/cdmi-container', 'fileExtension': '.cdmic'},
        '.cdmia': {'name': 'Cloud Data Management Interface (CDMI) - Capability', 'mimeType': 'application/cdmi-capability', 'fileExtension': '.cdmia'},
        '.ccxml': {'name': 'Voice Browser Call Control', 'mimeType': 'application/ccxml+xml,', 'fileExtension': '.ccxml'},
        '.atomsvc': {'name': 'Atom Publishing Protocol Service Document', 'mimeType': 'application/atomsvc+xml', 'fileExtension': '.atomsvc'},
        '.atomcat': {'name': 'Atom Publishing Protocol', 'mimeType': 'application/atomcat+xml', 'fileExtension': '.atomcat'},
        '.atom, .xml': {'name': 'Atom Syndication Format', 'mimeType': 'application/atom+xml', 'fileExtension': '.atom, .xml'},
        '.aw': {'name': 'Applixware', 'mimeType': 'application/applixware', 'fileExtension': '.aw'},
        '???': {'name': 'Andrew Toolkit', 'mimeType': 'application/andrew-inset', 'fileExtension': 'N/A'}
      };
    }

    return _contentTypeMapByExtension;
  }

}

enum RequestMethod{
  post,
  get,
}

extension RequestMethodExtension on RequestMethod{
  String get value {
    String value;
    switch(this){
      case RequestMethod.post:
        value = 'POST';
        break;
      case RequestMethod.get:
        value = 'GET';
        break;
      default:
        value = '<WHAT?>'; // Nunca debería dar este valor
    }

    return value;
  }
}